### PR TITLE
Fix bash errors

### LINKED ISSUE #7462: neofetch: what am I looking at?
## Description

Getting a bunch of bash errors any time I run it.

If you executed a specific command:
```shell
neofetch --ascii_distro Chrom*
```

Output:
```ruby
bash: _parse_usage: line 16: syntax error near unexpected token `('
bash: _parse_usage: line 16: ` -?(\[)+([a-zA-Z0-9?]))'
bash: error importing function definition for `_parse_usage'
bash: _longopt: line 6: syntax error near unexpected token `('
bash: _longopt: line 6: ` --!(no-*)dir*)'
bash: error importing function definition for `_longopt'
/usr/local/bin/neofetch: line 4783: warning: /home/chronos/user/.config/neofetch/config.conf: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
            .,:loool:,.               chronos@localhost 
        .,coooooooooooooc,.           ----------------- 
     .,lllllllllllllllllllll,.        OS: on Chrome OS x86_64 
    ;ccccccccccccccccccccccccc;       Host: Celes 1.1 
  'ccccccccccccccccccccccccccccc.     Kernel: 4.19.241-13212-ge9b0bab46475 
 ,ooc::::::::okO0000OOkkkkkkkkkkk:    Uptime: 18 days, 2 hours, 2 mins 
.ooool;;;;:xK0kxxxxxk0XK0000000000.   Packages: 271 (crew) 
:oooool;,;OKdddddddddddKX000000000d   Shell: sh 
lllllool;lNdllllllllllldNK000000000   Resolution: 1366x768 
llllllllloMdcccccccccccoWK000000000   WM: chrome 
;cllllllllXXc:::::::::c0X000000000d   Terminal: chrome 
.ccccllllllONkc;,,,;cxKK0000000000.   CPU: Intel Celeron N3050 (2) @ 2.160GHz 
 .cccccclllllxOOOOOOkxO0000000000;    GPU: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
  .:cccccccclllllllloO0000000OOO,     Memory: 2144MiB / 3885MiB 
    ,:ccccccccclllcd0000OOOOOOl.
      '::cccccccccdOOOOOOOkx:.                                
        ..,::ccccxOOOkkko;.                                   
            ..,:dOkxl:.
```

## Versions and system information

***
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `4.19.241-13212-ge9b0bab46475`

- Chromebrew version: `1.25.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: cf97ef9 `Git w/o musl, install.sh modified to work w/o git in bootstrap. (#7436) (2 days ago)`

- OS variant: `Chrome OS`
- OS version: `celes-release/R103-14816.131.0`
- OS channel: `stable-channel`
***

## Additional information

oh yeah, what's up with that gem debug error, anyways?

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #7462

## Description
- Fix wayland `env.d` file which didn't have a closing `set +a`. This was the primary problem.
- These are bash fixes to make startup more robust.
  - Change sommelier startup scripts:
    - Modification of `/usr/local/etc/bash.d/sommelier` in the sommelier package thus:
      `source /usr/local/bin/startsommelier`
    - Modification of `/usr/local/bin/startsommelier` in the sommelier package thus:
      Change `exit 1` to `return 1`. 
  - Move loading of Chromebrew bash (if installed) to /usr/local/etc/profile, so it is loaded as early as possible. This is actually in https://github.com/chromebrew/crew-profile-base/pull/10 and is independent, but bash is modified in this PR not to have this logic in `/usr/local/etc/bash.d/bash`.
  - Remove `bash.d` file from bash_completion since to avoid issues with it being loaded twice.

- _Tested by opening multiple subshells with wayland and sommelier installed._

## Additional information

Works properly:
- [x] `x86_64` (tested on hardware - sommelier still works.)
- [x] `i686` (tested in container)
- [x] `armv7l` (tested in container)

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=fix_bash  CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/sommelier.rb [hunk 1]
```diff
@@ -56,7 +49,9 @@ def self.preflight
     when 'i686', 'x86_64'
       @container_check = `/usr/bin/crossystem inside_vm` == '1'
     end
-    abort 'This package is not compatible with your device :/'.lightred unless File.socket?('/var/run/chrome/wayland-0') || @container_check
+    return if File.socket?('/var/run/chrome/wayland-0') || @container_check
+
+    abort 'This package is not compatible with your device :/'.lightred
```
Comment (uberhacker) [inline packages/sommelier.rb:54]: Would this logic be better?
case ARCH
    when 'armv7l', 'aarch64'
      @container_check = File.exist?('/.dockerenv')
    when 'i686', 'x86_64'
      @container_check = `/usr/bin/crossystem inside_vm` == '1'
    else
      abort 'This package is not compatible with your device :/'.lightred
    end
    return if File.socket?('/var/run/chrome/wayland-0') || @container_check
```

Comment (satmandu) [reply packages/sommelier.rb:54]: The suggestion is this:
```
  def self.preflight
    case ARCH
    when 'armv7l', 'aarch64'
      @container_check = File.exist?('/.dockerenv')
    when 'i686', 'x86_64'
      @container_check = /usr/bin/crossystem inside_vm == '1'
    else
      abort 'This package is not compatible with your device :/'.lightred
    end
    return if File.socket?('/var/run/chrome/wayland-0') || @container_check
    
  end
```

The abort happens if ARCH isn't armv7l, aarch64, x86_64, i686. That isn't useful because that will always be false.  We want the abort to happen if return doesn't happen.

Comment (uberhacker) [reply packages/sommelier.rb:54]: Oh, so this would abort for i686 then?

**Review by uberhacker — APPROVED** [review]
