### PR TITLE
Fix crew help search

### LINKED ISSUE #9834: 🐞 Bug `crew help search` does not interpolate output correctly
```
$ crew help search
Look for package(s).
Usage: crew search [-v|--verbose] [<pattern> ...]
Both the name and description of packages will be searched.
If the package color is " + "green".lightgreen + ", it means the package is installed.
If the package color is " + "red".lightred + ", it means the architecture is not supported.
If the package color is " + "blue".lightblue + ", it means the architecture is supported but the package is not installed.
The <pattern> string can also contain regular expressions.
If `-v` or `--verbose` is present, the homepage, version and license of found packages will be displayed.
Examples:
  crew search ^lib".lightblue + " will display all packages with a name or description that starts with `lib`.
  crew search audio".lightblue + " will display all packages with `audio` in the name or description.
  crew search -v git".lightblue + " will display all packages with `git` in the name or description along with homepage, version and license.
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #9834.

### CODE REVIEW

File: commands/help.rb [hunk 1]
```diff
@@ -98,19 +98,25 @@ def self.help(command)
...
+      search_audio = 'crew search audio'.lightblue
+      search_git = 'crew search -v git'.lightblue
       puts <<~EOT
         Look for package(s).
         Usage: crew search [-v|--verbose] [<pattern> ...]
         Both the name and description of packages will be searched.
-        If the package color is " + "green".lightgreen + ", it means the package is installed.
-        If the package color is " + "red".lightred + ", it means the architecture is not supported.
-        If the package color is " + "blue".lightblue + ", it means the architecture is supported but the package is not installed.
+        If the package color is #{green}, it means the package is installed.
```
Comment (Zopolis4) [inline commands/help.rb:111]:
```
If the package color is #{'green'.lightgreen}, it means the package is installed.
```

Does this work?

Comment (uberhacker) [reply commands/help.rb]: Yes but you were supposed to fix this days ago. :-P

**Review by satmandu — APPROVED** [review]
