### PR TITLE
Fix for require issues with highline and glibc 2.37 refactor

### LINKED ISSUE #10359: Unable to build CMake packages
**Describe the bug**
The cmake buildsystem was broken by #10335.

**To Reproduce**

1. Please indicate where the command(s) were executed.

`satmandu/crewbuild:m90-x86_64` container

2. I executed the command(s) below:
      ```shell
      crew reinstall -s libxml2
      ```

      Output:

      ```
      libxml2: Libxml2 is the XML C parser and toolkit developed for the Gnome project.
      Performing pre-flight checks...
      Downloading source...
      Cannot find cached git repository. 😔 Will download.
      Initialized empty Git repository in /usr/local/tmp/crew/libxml2.20240826002845.dir/.git/
      remote: Enumerating objects: 3452, done.
      remote: Counting objects: 100% (3452/3452), done.
      remote: Compressing objects: 100% (2167/2167), done.
      remote: Total 3452 (delta 865), reused 2850 (delta 707), pack-reused 0 (from 0)
      Receiving objects: 100% (3452/3452), 3.39 MiB | 2.74 MiB/s, done.
      Resolving deltas: 100% (865/865), done.
      From https://gitlab.gnome.org/GNOME/libxml2
       * tag               v2.13.3    -> FETCH_HEAD
      HEAD is now at 3b1742b Release v2.13.3
      Repository downloaded.
      Caching downloaded git repo...
      Git repo cached.
      Building from source, this may take a while...
      Additional cmake_options being used: <no pre_cmake_options> -DLIBXML2_WITH_PYTHON=OFF \
          -DLIBXML2_WITH_LZMA=OFF \
          -DLIBXML2_WITH_ICU=ON
      CMake Error: -C must be followed by a file name.
      CMake Error: Run 'cmake --help' for all supported options.
      Command "bash -c  mold -run cmake -C  -B builddir -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_LIBRARY_PATH=/usr/local/lib64 -DCMAKE_C_FLAGS='-O2 -pipe -ffat-lto-objects -fPIC   -flto=auto' -DCMAKE_CXX_FLAGS='-O2 -pipe -ffat-lto-objects -fPIC   -flto=auto' -DCMAKE_EXE_LINKER_FLAGS='-flto=auto ' -DCMAKE_LINKER_TYPE=MOLD -DCMAKE_SHARED_LINKER_FLAGS='-flto=auto ' -DCMAKE_MODULE_LINKER_FLAGS='-flto=auto ' -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_BUILD_TYPE=Release -DLIBXML2_WITH_PYTHON=OFF \
          -DLIBXML2_WITH_LZMA=OFF \
          -DLIBXML2_WITH_ICU=ON" failed, retrying with "-j1"...
      CMake Error: -C must be followed by a file name.
      CMake Error: Run 'cmake --help' for all supported options.
      There was a build error.
      ```
**Expected behavior**
The build to work successfully

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
/usr/local/bin/crew:1843:<main>:The last update was 3 min, 35 seconds ago.
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `true`

- Chromebrew version: `1.51.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 8bf154910 `Fix repology workflow again by installing highline (#10354) (20 hours ago)`

- OS variant: `Chrome OS`
- OS version: `nocturne-release/R90-13816.82.0`
- OS channel: `stable-channel`

</details>

***

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #10359 #10350 #10352 

## Description
- Refactors `fixup.rb` and `remove.rb` to make them work together more robustly when updating from a much older crew. (Also this uses the non-symbolized json, and then updates the crew json in memory whether symbolized or not.)
- Fixup also uses an `@installed_packages` `set` that can be searched much faster with `@installed_packages.include?(pkg_name)`. We should consider making this global as this should be much faster for checking if stuff is installed, which we do a lot of, since we don't have to interate through all the packages each time.
- `const.rb` was refactored to allow it to be loaded again without more annoying warnings.
- Adjusts commands/list .rb to use the non-symbolized json.
- Adjusts `commands/remove.rb` to not require a verbose argument since `const.rb` is now being pulled in.
- Refactors the glibc 2.37 packages.
- Fixes issues with `highline` includes causing problems with updates from older crew releases.

## And one more thing...
- Also, we should really have code to check to see if the device.json has been updated, and if so to reload the json accordingly, especially since we are now invoking outside programs that might save the json. (This took me a while to debug.)

Tested & Working properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 
##

### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=requirefix crew update \
&& yes | crew upgrade && \
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=requirefix crew update \
&& yes | crew upgrade 
```

### CODE REVIEW

File: lib/buildsystems/cmake.rb [hunk 1]
```diff
@@ -5,16 +5,16 @@ class CMake < Package
 
   attr_accessor :cmake_build_relative_dir
```
Comment (Zopolis4) [inline lib/buildsystems/cmake.rb:6]: Why is this not a property?

File: lib/fixup.rb [hunk 2]
```diff
@@ -3,30 +3,52 @@
...
 
-CREW_VERBOSE = ARGV.intersect?(%w[-v --verbose]) unless defined?(CREW_VERBOSE)
+CREW_VERBOSE ||= ARGV.intersect?(%w[-v --verbose])
 
-HOME = '/home/chronos/user' unless defined?(HOME)
-CREW_PREFIX = '/usr/local' unless defined?(CREW_PREFIX)
-CREW_LIB_PATH = File.join(CREW_PREFIX, 'lib/crew') unless defined?(CREW_LIB_PATH)
-CREW_CONFIG_PATH = File.join(CREW_PREFIX, 'etc/crew') unless defined?(CREW_CONFIG_PATH)
-CREW_META_PATH = File.join(CREW_CONFIG_PATH, 'meta') unless defined?(CREW_CONFIG_PATH)
+HOME ||= '/home/chronos/user'
```
Comment (Zopolis4) [inline lib/fixup.rb:33]: Why do we need to do this complex dance of conditional assignment for these variables? Why can't we just require const.rb?

File: .rubocop.yml [hunk 3]
```diff
@@ -24,6 +24,10 @@ Lint/Debugger:
   DebuggerMethods:
     Pry: ~
 
+# Need to allow reloading const.rb from fixup.rb
+Lint/OrAssignmentToConstant:
```
Comment (Zopolis4) [inline .rubocop.yml:28]: If we end up needing to use conditional assignment in const.rb, then disable this rule for that file only, rather than the entire codebase.

File: lib/buildsystems/cmake.rb [hunk 4]
```diff
@@ -5,16 +5,16 @@ class CMake < Package
...
-    super
-    @cmake_build_relative_dir = '.'
-  end
-
   def self.build
-    puts "Additional cmake_options being used: #{@pre_cmake_options.nil? ? '<no pre_cmake_options>' : @pre_cmake_options} #{@cmake_options.nil? ? '<no cmake_options>' : @cmake_options}".orange
+    @cmake_build_relative_dir ||= '.'
     @crew_cmake_options = @no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
+    puts "Additional cmake options being used:".orange
+    method_list = methods.grep(/cmake_/).delete_if { |i| send(i).blank? }
```
Comment (Zopolis4) [inline lib/buildsystems/cmake.rb:12]: this feels like a much more complicated solution than the previous method of a puts statement, and also looks like it doesn't provide as much information as before in cases where the option is nil?

File: lib/package.rb [hunk 5]
```diff
@@ -27,7 +27,6 @@ def require_gem(gem_name_and_require = nil, require_override = nil)
 
 def agree_with_default(yes_or_no_question_msg, character = nil, default:)
   yes_or_no_question = yes_or_no_question_msg.lightpurple
-  require_gem('highline')
```
Comment (Zopolis4) [inline lib/package.rb:30]: We use highline in the lines immediately following, so we should probably still require it in `lib/package.rb`

**Review by Zopolis4 — CHANGES_REQUESTED** [review]

File: lib/buildsystems/cmake.rb (hunk 1 above)
Comment (satmandu) [reply lib/buildsystems/cmake.rb:6]: Good call. Should probably only be a property...

File: lib/fixup.rb (hunk 2 above)
Comment (satmandu) [reply lib/fixup.rb:33]: It's a good question!

We `load` fixup.rb... but since we already have const.rb required, as I understand it... it won't be loaded again unless we use `load`, which gives us a ton of `warning: already initialized constant ` errors.

The problem is that we NEED const.rb reloaded, because otherwise we will call remove.rb for a package that fixup wants to remove, but then remove.rb will die if crew update was run so long ago the in-memory const.rb doesn't have an essential_packages array constant loaded.

File: .rubocop.yml (hunk 3 above)
Comment (satmandu) [reply .rubocop.yml:28]: Good idea.

File: lib/package.rb (hunk 5 above)
Comment (satmandu) [reply lib/package.rb:30]: Agreed, but I'm loading highline from `crew` now, so it should already be loaded. (Otherwise I was getting issues with stuff complaining about highline not being loaded.)

File: lib/buildsystems/cmake.rb (hunk 4 above)
Comment (satmandu) [reply lib/buildsystems/cmake.rb:12]: By nil you mean the option isn't set? Because in that case it just doesn't show the method.

Comment (Zopolis4) [reply lib/buildsystems/cmake.rb:12]: Whereas before it would print something like <no_cmake_options>, right?

File: lib/fixup.rb (hunk 2 above)
Comment (satmandu) [reply lib/fixup.rb:33]: I am still getting the warning: already initialized constant  errors though... Any suggestions on how to deal with this?

Comment (Zopolis4) [reply lib/fixup.rb:33]: Oh, that is tricky. Couple things: I've removed the need for essential_deps in #9832, so that's a possible solution.

In the short term, couldn't we load essential_deps from device.json in commands/remove.rb and bypass the need for it to be present in lib/const.rb?

File: lib/package.rb (hunk 5 above)
Comment (Zopolis4) [reply lib/package.rb:30]: Fair, although I think it's still a good idea to require the necessary files rather than relying on them being implicitly present. (i.e. if we only load lib/package.rb and it's not run through bin/crew, which is the case for all our tests.)

File: lib/fixup.rb (hunk 2 above)
Comment (Zopolis4) [reply lib/fixup.rb:33]: > I am still getting the warning: already initialized constant  errors though... Any suggestions on how to deal with this?

My suggestion is to take the warning at face value-- the constants are already initialised, so we don't need to set them again.

File: lib/package.rb [hunk 6]
```diff
@@ -27,7 +27,6 @@ def require_gem(gem_name_and_require = nil, require_override = nil)
```
Comment (Zopolis4) [inline lib/package.rb:27]: We also don't need to define `require_gem` in `lib/package.rb` anymore, as a regular require should work here as highline will have been installed before we get here.

File: commands/remove.rb [hunk 7]
```diff
@@ -1,5 +1,6 @@
 require 'fileutils'
 require_relative '../lib/const'
+load '../lib/const.rb' if CREW_ESSENTIAL_PACKAGES.blank?
```
[the remark this answers is not in the document]
Comment (Zopolis4) [reply commands/remove.rb:3]: image
from testing on a local docker installation without the essential_deps field in device.json

File: commands/remove.rb [hunk 8]
```diff
@@ -18,7 +39,12 @@ def self.remove(pkg, verbose)
     # their dependencies, as those are needed for ruby and crew to run,
     # and thus should not be removed.
     # essential_deps = recursive_deps(CREW_ESSENTIAL_PACKAGES)
-    essential_deps = device_json[:essential_deps]
+    if device_json[:essential_deps].blank?
```
Comment (Zopolis4) [inline commands/remove.rb:42]: is there a situation in which this will be empty? it'll be nil if the field isnt in device.json, which does happen and is the cause of the issue, but I can't think of a scenario in which it'll be empty.

File: lib/fixup.rb (hunk 2 above)
Comment (satmandu) [reply lib/fixup.rb:33]: Yes, but it looks really ugly... and we don't want to throw unnecessary warnings. :/

File: commands/remove.rb (hunk 8 above)
Comment (satmandu) [reply commands/remove.rb:42]: I'm just trying to handle the nil error... .`nil?` is complaining... but that could be a race condition from having older code in the mix. I'm just opening the M121 container for testing...

File: lib/fixup.rb (hunk 2 above)
Comment (Zopolis4) [reply lib/fixup.rb:33]: Hence why I am suggesting not defining the constants again in lib/fixup.rb (i.e. why do we need to define HOME again?)

File: lib/buildsystems/qmake.rb [hunk 9]
```diff
@@ -4,7 +4,7 @@ class Qmake < Package
   property :qmake_build_extras, :qmake_install_extras
 
   def self.build
-    system "QMAKE_CXX='g++ #{ARCH == 'x86_64' && LIBC_VERSION.to_f >= 2.35 ? File.join(CREW_LIB_PREFIX, 'libC.so.6').to_s : ''}' qmake"
+    system "QMAKE_CXX='g++ #{ARCH == 'x86_64' && Gem::Version.new(LIBC_VERSION.to_s) >= Gem::Version.new('2.35') ? File.join(CREW_LIB_PREFIX, 'libC.so.6').to_s : ''}' qmake"
```
Comment (Zopolis4) [inline lib/buildsystems/qmake.rb:7]: Why this change? Isn't it just a more complicated way of doing the same thing?

Comment (satmandu) [reply lib/buildsystems/qmake.rb:7]: There was a discussion earlier of version comparisons possibly breaking in the glibc builds, so as per that I've been unifying the usage with the gem version comparisons.

Comment (uberhacker) [reply lib/buildsystems/qmake.rb:7]: Yes, when comparing versions 2.4 is lower than 2.37, however 2.40 is higher than 2.37.  That is where the potential problem may occur.

Comment (Zopolis4) [reply lib/buildsystems/qmake.rb:7]: Yes, but the lowest glibc version we will encounter is 2.23, so we don't need to worry about that. All the glibc versions we deal with have double digit minor versions.

**Comment by satmandu** [comment]
FYI I'm really mucking around here, so this branch isn't usable at the moment...

**Comment by Zopolis4** [comment]
On that note, in future maybe split up separate changes to PRs? This PR is attempting to fix at least 3 issues by my count, all of which are pretty urgent, and because all the changes are combined, difficulties in solving one is holding up the fixes for all the others.

**Comment by satmandu** [comment]
Yeah that's on me. Sorry about that.

File: lib/package_utils.rb [hunk 10]
```diff
@@ -3,10 +3,20 @@
...
+  keepers = keeper_keys.to_set
+  arr.map { |h| h.select { |k, _| keepers.include?(k) } }
+end
+
 class PackageUtils
-  def self.installed?(pkg_name)
+  def self.generate_installed_packages
     device_json = JSON.load_file(File.join(CREW_CONFIG_PATH, 'device.json'))
-    return device_json['installed_packages'].any? { |elem| elem['name'] == pkg_name }
+    return keep_keys(device_json['installed_packages'], ['name']).flat_map(&:values).to_set
```
Comment (Zopolis4) [inline lib/package_utils.rb:14]: Given that we have to iterate over the array anyways to convert it to a set, we aren't actually getting speedups here, unfortunately:
image
```ruby
require 'json'
require 'set'
require 'benchmark'

CREW_CONFIG_PATH = '/usr/local/etc/crew'

# Method 1: Direct check for package name
def method_1(pkg_name)
  device_json = JSON.load_file(File.join(CREW_CONFIG_PATH, 'device.json'))
  device_json['installed_packages'].any? { |elem| elem['name'] == pkg_name }
end

# Method 2: Using keep_keys to filter and check
def keep_keys(arr, keeper_keys)
  keepers = keeper_keys.to_set
  arr.map { |h| h.select { |k, _| keepers.include?(k) } }
end

def method_2(pkg_name)
  device_json = JSON.load_file(File.join(CREW_CONFIG_PATH, 'device.json'))
  target = keep_keys(device_json['installed_packages'], ['name']).flat_map(&:values).to_set
  target.include?(pkg_name)
end

# Package name to search for
pkg_name = 'example_package_name'
installed_pkg_name = 'ruby'

# Benchmarking the two methods
Benchmark.bm do |x|
  x.report("Method 1, not installed package: ") { 1000.times { method_1(pkg_name) } }
  x.report("Method 2, not instapped package: ") { 1000.times { method_2(pkg_name) } }
  x.report("Method 1, installed package: ") { 1000.times { method_1(installed_pkg_name) } }
  x.report("Method 2, instapped package: ") { 1000.times { method_2(installed_pkg_name) } }
end
```

Comment (satmandu) [reply lib/package_utils.rb]: Trying to only iterate over the array once... That means creating sets for installed packages once.

Comment (satmandu) [reply lib/package_utils.rb]: So the idea is to have the one installed_packages set being used for multiple `installed?` checks.

Can you benchmark that?

**Comment by satmandu** [comment]
Argh. Package rename is still broken. I'm probably reloading the json before writing it...

**Comment by Zopolis4** [comment]
you've got stuff still symbolised in command/remove.rb

maybe a quick grep for 'device_json[:' to ensure u don't miss anything

**Comment by satmandu** [comment]
> you've got stuff still symbolised in command/remove.rb
> 
> maybe a quick grep for 'device_json[:' to ensure u don't miss anything

But that shouldn't matter, because we aren't passing symbolized stuff back and forth between remove.rb and everything else.

**Comment by satmandu** [comment]
Oh, we also need a superseded_by field in our update array.

If py3_pre_commit is installed, then we can remove linter.

Also, if a package file isn't there, prompt to remove package if marked as installed, especially if there aren't any file lists present?

Seeing that issue now with incomplete removal...

File: lib/fixup.rb (hunk 2 above)
Comment (satmandu) [reply lib/fixup.rb]: HOME is no longer defined again.

File: commands/remove.rb (hunk 8 above)
Comment (satmandu) [reply commands/remove.rb]: Fixed the root cause.

File: lib/buildsystems/qmake.rb (hunk 9 above)
Comment (satmandu) [reply lib/buildsystems/qmake.rb:7]: Honestly I don't care which way we go on this. I just want it to be uniform if possible. I think that glibc versions are a special case, and we should avoid special cases when possible...

File: lib/fixup.rb (hunk 2 above)
Comment (Zopolis4) [reply lib/fixup.rb]: It's not just HOME-- why do we need to define most of these constants again, and why do we need to set all the constants in `lib/const.rb` as `||=` when we only redefine a few of them?

and again, all of this could be bypassed if we didn't load `essential_deps` from device.json

File: lib/buildsystems/qmake.rb (hunk 9 above)
Comment (Zopolis4) [reply lib/buildsystems/qmake.rb:7]: Let's unify it to just the float comparison-- `Gem::Version.new` is overkill here.

Comment (uberhacker) [reply lib/buildsystems/qmake.rb:7]: I just explained why we need to compare versions semantically a few comments earlier.

Comment (uberhacker) [reply lib/buildsystems/qmake.rb:7]: Bedtime reading material: https://semver.org/

File: lib/fixup.rb (hunk 2 above)
Comment (satmandu) [reply lib/fixup.rb]: You need the `||=` construction because we are using ` load 'lib/const.rb'` instead of using `require 'lib/const.rb'` to reload `const.rb` from `fixup.rb`, and that triggers tons of errors about trying to redefine constants.

(We reload const.rb from fixup.rb right after a git pull, so we may have new or changed constants there we need to check for.)

`||=` does a _define if not already defined_, which appears to work for most stuff, except anything we are defining with a call to check an environment variable, so that's mostly ideal for a file of constant definitions that we are about to reload.

Comment (Zopolis4) [reply lib/fixup.rb]: We could try a system call to `lib/fixup.rb` so its not dealing with any scope problems and loads everything afresh? (i.e. `system ./lib/fixup.rb` and just have it be a regular script)

File: lib/buildsystems/qmake.rb (hunk 9 above)
Comment (Zopolis4) [reply lib/buildsystems/qmake.rb:7]: > I just explained why we need to compare versions semantically a few comments earlier.

And I explained a few comments later why that is not relevant in the case of comparing glibc versions.

glibc version 2.4 was released in 2005, 5 years before the first chromebook released. and again, the lowest glibc version we will encounter is 2.23.

File: lib/fixup.rb [hunk 11]
```diff
@@ -4,30 +4,107 @@
...
+             end
+  require requires
+end
+require_gem('highline')
 
 # All needed constants & variables should be defined here in case they
 # have not yet been loaded or fixup is being run standalone.
 
-CREW_VERBOSE = ARGV.intersect?(%w[-v --verbose]) unless defined?(CREW_VERBOSE)
+CREW_VERBOSE ||= ARGV.intersect?(%w[-v --verbose]) unless defined?(CREW_VERBOSE)
```
Comment (Zopolis4) [inline lib/fixup.rb:32]: You don't need `unless defined?(CREW_VERBOSE)` if you're using `||=`, do you?

Comment (satmandu) [reply lib/fixup.rb:32]: You would think not, but for some reason for the way these variables are being set ruby complains otherwise. 🤷🏿

Comment (satmandu) [reply lib/fixup.rb:32]: I thought it was annoying too...

Every time I have both is because the `||=` wasn't sufficient.

**Comment by satmandu** [comment]
I'm getting this only on the arm container:

```
chronos@rpi51-armv7l:2.27 M91 /usr/local/lib/crew/packages (master >|SPARSE)$ crew whatprovides bin/convert
/usr/local/lib/crew/lib/package.rb:104:in `read': no implicit conversion of nil into String (TypeError)

    class_eval(File.read(pkg_file, encoding: Encoding::UTF_8), pkg_file) unless const_defined?("Package::#{class_name}")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /usr/local/lib/crew/lib/package.rb:104:in `load_package'
        from /usr/local/lib/crew/commands/whatprovides.rb:11:in `block in whatprovides'
        from /usr/local/lib/crew/commands/whatprovides.rb:7:in `each'
        from /usr/local/lib/crew/commands/whatprovides.rb:7:in `flat_map'
        from /usr/local/lib/crew/commands/whatprovides.rb:7:in `whatprovides'
        from /usr/local/bin/crew:1804:in `block in whatprovides_command'
        from /usr/local/bin/crew:1803:in `each'
        from /usr/local/bin/crew:1803:in `whatprovides_command'
        from /usr/local/bin/crew:1826:in `<main>'
```

Any idea where this is from?

**Comment by satmandu** [comment]
@Zopolis4 @supechicken Any ideas?

**Comment by satmandu** [comment]
(I don't think there are any changes relevant to package.rb that would cause that in this PR?, and it isn't an issue on x86_64 or i686...)

**Comment by satmandu** [comment]
I need to add a unit test for `crew whatprovides`...

**Comment by satmandu** [comment]
Ok `crew whatprovides` is broken on arm on master, so this PR isn't to blame, so I'm flipping this off of draft again. That's another issue that can be fixed in the future...

File: lib/package.rb (hunk 5 above)
Comment (satmandu) [reply lib/package.rb:30]: Resolving since a `require_gem('highline')` is still in `lib/package.rb`.

File: lib/package_utils.rb (hunk 10 above)
Comment (satmandu) [reply lib/package_utils.rb]: Let's figure this portion out another day, since this is only in `lib/fixup.rb` for now...

File: lib/buildsystems/qmake.rb (hunk 9 above)
Comment (uberhacker) [reply lib/buildsystems/qmake.rb:7]: Remember, versions can be of the form 2.37.1.  So, if LIBC_VERSION is converted to float in this instance, the value would be 2.37 which compared to an earlier version may or may not yield the desired result.  We cannot assume glibc will always have one decimal point.  A lot of the earlier glibc versions had 2 decimal points so we better use the proper version comparison.

File: packages/glibc_lib237.rb [hunk 12]
```diff
@@ -32,7 +33,7 @@ def self.install
     @filelist = File.readlines(@filelist_path, chomp: true).sort
 
     @filelist.each do |filename|
-      next unless filename.include?('.so') || filename.include?('bin/')
+      next unless (filename.include?('.so') || filename.include?('bin/')) && File.file?(filename)
```
Comment (uberhacker) [inline packages/glibc_lib237.rb:36]: Should `File.file?(filename)` be the first comparison?
```
next unless File.file?(filename) && (filename.include?('.so') || filename.include?('bin/'))
```

Comment (satmandu) [reply packages/glibc_lib237.rb:36]: Good point.

File: packages/ruby_pry.rb [hunk 13]
```diff
@@ -1,5 +1,4 @@
 require 'buildsystems/ruby'
-require 'highline/import'
```
Comment (uberhacker) [inline packages/ruby_pry.rb:2]: This is a good fix and much needed.

File: packages/glibc_lib237.rb (hunk 12 above)
Comment (satmandu) [reply packages/glibc_lib237.rb:36]: Is it better to do a string comparison before we look for a file on disk?

Comment (satmandu) [reply packages/glibc_lib237.rb:36]: (Because the string comparison is faster than checking to see if the file is there?)

**Review by uberhacker — APPROVED** [review]
