### PR TITLE
Fix glibc symlinks not being made properly

### LINKED ISSUE #7328: remmina is missing rdp plugin
## Description

remmina has rdp plugin by default in linux but its missing here. i tried the -s option too but it bugged out. i tried searching for the plugin with crew but couldnt find anything
If you executed a specific command:
```shell
# your command here
```
remmina
Output:
```
# output of your command here
```

## Versions and system information

***
***

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #7328

- Previously the glibc postinstall was making symlinks for the system provided libraries in here:
```
@libraries = %w[ld libBrokenLocale libSegFault libanl libc libcrypt
                    libdl libm libmemusage libmvec libnsl libnss_compat libnss_db
                    libnss_dns libnss_files libnss_hesiod libpcprofile libpthread
                    libresolv librlv librt libthread_db-1.0 libutil]
```
exclusively from `/#{ARCH_LIB}/` but many of these files are actually in `/usr/#{ARCH_LIB}/`, so we need to symlink from there.
BUT we also have to make sure we select only the libraries we want and don't wildcard glob onto everything... AND we need to avoid selecting folders.

- Upon crew upgrade this should force glibc to reinstall, which will generate the symlinks properly.

Works properly:
- [x] `x86_64` 
- [x] `i686`
- [x] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_fix2 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
@kunver400 

Please try this:
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_fix2 CREW_TESTING=1 crew update ; crew upgrade
```

File: packages/glibc.rb [hunk 1]
```diff
@@ -598,7 +598,15 @@ def self.postinstall
       puts "System glibc version is #{LIBC_VERSION}.".lightblue
       puts 'Creating symlinks to system glibc version to prevent breakage.'.lightblue
       @libraries.each do |lib|
-        Dir.glob("/#{ARCH_LIB}/#{lib}*").each do |f|
+        # Reject entries which aren't libraries ending in .so, and which aren't files.
+        Dir.glob("/#{ARCH_LIB}/#{lib}.so*").reject { |f| File.directory?(f) }.each do |f|
```
Comment (uberhacker) [inline packages/glibc.rb:602]: Use `Dir["/#{ARCH_LIB}/#{lib}.so*"]` instead?

**Review by uberhacker — CHANGES_REQUESTED** [review]
See comments.

File: packages/glibc.rb [hunk 2]
```diff
@@ -598,7 +598,15 @@ def self.postinstall
...
+          if `file #{f} | grep "shared object"`
+            g = File.basename(f)
+            FileUtils.ln_sf f.to_s, g.to_s
+          end
+        end
+        # Reject entries which aren't libraries ending in .so, and which aren't files.
+        Dir.glob("/usr/#{ARCH_LIB}/#{lib}.so*").reject { |f| File.directory?(f) }.each do |f|
```
[the remark this answers is not in the document]
Comment (satmandu) [reply packages/glibc.rb]: done.

File: packages/glibc.rb (hunk 1 above)
Comment (satmandu) [reply packages/glibc.rb]: done.

**Review by uberhacker — APPROVED** [review]
