### PR TITLE
Fixup gcc_lib and crew update for very old milestone installs

### LINKED ISSUE #9901: 🐞 Bug Lib_GCC error
**Describe the bug**
During the install.sh script, when it does the `crew install core` command, i get this error when its trying to install gcc_lib

```gcc_lib: GCC shared libs except libgccjit
Skipping source download...
Building from source, this may take a while...
Preconfiguring package...
Installing Gcc_build to pull files for build...
File list for Gcc_build does not exist!
An error occured during the installation :/
```

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): crosh

2. I executed the command(s) below:
      ```shell
      bash <(curl -L git.io/vddgY) && . ~/.bashrc
      ```
**Expected behavior**

Not have an error there.

**Screenshots**

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.48.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 

- OS variant: `Chrome OS`
- OS version: `edgar-release/R103-14816.131.0`
- OS channel: `stable-channel`

</details>
***

### PR DESCRIPTION
**Pull request by satmandu**
Probably Fixes #9901 

- These issues come up when I open the M106 container...

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=old_install_fix crew update
```

### CODE REVIEW

File: bin/crew [hunk 1]
```diff
@@ -4,7 +4,14 @@ require 'digest/sha2'
 require 'json'
 require 'fileutils'
 require 'tmpdir'
-require_relative '../commands/const'
+begin
+  require_relative '../commands/const'
+rescue LoadError
+  # Older crew installs won't have the commands dir in the sparse checkout,
```
Comment (Zopolis4) [inline bin/crew:10]: Don't we already handle this in lib/fixup.rb?

File: lib/const.rb [hunk 2]
```diff
@@ -50,7 +50,7 @@
 ARCH_LIB        = "lib#{CREW_LIB_SUFFIX}"
 
 # Glibc version can be found from the output of libc.so.6
-LIBC_VERSION = Etc.confstr(Etc::CS_GNU_LIBC_VERSION).split.last
+LIBC_VERSION = ENV.fetch('LIBC_VERSION', Etc.confstr(Etc::CS_GNU_LIBC_VERSION).split.last )
```
Comment (Zopolis4) [inline lib/const.rb:53]: What was the problem with the old method?

**Review by Zopolis4 — CHANGES_REQUESTED** [review]

File: bin/crew (hunk 1 above)
Comment (satmandu) [reply bin/crew:10]: The error happens when loading crew, before we get to fixup.

File: lib/const.rb (hunk 2 above)
Comment (satmandu) [reply lib/const.rb:53]: Trying to set `LIBC_VERSION` manually for when we need to override it, as when we are building the various packages with that used in the version field.

**Comment by satmandu** [comment]
What's the requested change @Zopolis4 ?

File: bin/crew (hunk 1 above)
Comment (Zopolis4) [reply bin/crew:10]: But how will we have updated to a newer state without running fixup?

Comment (satmandu) [reply bin/crew:10]: Git pull has already happened at this point. Disabling the sparse checkout unhides all the files needed.

Comment (satmandu) [reply bin/crew:10]: The git pull leaves crew in a broken state, because the commands dir is not yet part of the sparse checkout.

**Review by Zopolis4 — APPROVED** [review]
Not entirely sure about the sparse-checkout stuff, but i'll look into that without holding up an install fix.

**Comment by jacobh12349** [comment]
So, do i just run the install script again to fix it?

**Comment by jacobh12349** [comment]
> So do i just run the install script again to fix it?

I'm just gonna do that now, and see if it works, and come back if it doesn't.

**Comment by jacobh12349** [comment]
I've also seen this while the script is running too, but the script still continues running though, so i dont know if its that important.

```
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by jacobh12349** [comment]
Ya, gcc_lib installed fine now, and the rest of the install script all worked fine now too, thx
