### PR TITLE
fixup prompts

### LINKED ISSUE #7812: 🐞 Bug Crew does not wait for responses to postinstall prompts when an install also requires dependencies to be installed
Queries in the `postinstall` give users agency over their install. Automatically defaulting to answers is a bug, unless that default intentionally has a timeout connected automatic selection.

Working prompt behavior in a new container or install:
```
yes | crew install `comm -13 <(crew -d list installed | sort) <(crew deps -b -d "firefox" | sort)`
crew install firefox
```
Broken prompt behavior in a new container or install:
```
crew install firefox
```
Output as seen:
image

(This also affects `vim` and `neovim` and probably all other installs with queries in the `postinstall`.)

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #7812 

- Get string, chomp it, downcase it, and then look for `''`, `y`, and `yes` in input string. This allows one to hit enter after the input without having that newline passed to another prompt.

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=fix_prompts CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/php.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ def self.preflight
     puts '8.2 = PHP 8.2.1'
     puts '  0 = Cancel'
 
-    while version = $stdin.gets.chomp
+    while version = $stdin.gets.chomp.downcase
```
Comment (uberhacker) [inline packages/php.rb:31]: No need for `.downcase` here since all the expected input will be numeric.

**Review by uberhacker — APPROVED** [review]

File: packages/php.rb (hunk 1 above)
Comment (satmandu) [reply packages/php.rb:31]: Ah well, you can fix it on the next update. :)
