### PR TITLE
squashfs => 4.6.1

### LINKED ISSUE #8921: [AMD StoneyRidge] `squashfs` segfault
The binaries in the package `squashfs` crash with a segmentation fault on AMD StoneyRidge machines, and need to be rebuilt.

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #8921

Builds properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=squashfs crew update
```

### CODE REVIEW

**Comment by Zopolis4** [comment]
Would you mind rebasing this on master? I just wanna check that the new actions are working correctly-- I tested them as well as I could locally, but I'd just like to be sure.

**Comment by satmandu** [comment]
I rebased the other PRs...

File: packages/squashfs.rb [hunk 1]
```diff
@@ -2,46 +2,53 @@
...
     FileUtils.cd('squashfs-tools') do
       system "sed -i '5iLZ4_SUPPORT = 1' Makefile"
       system "sed -i '6iLZO_SUPPORT = 1' Makefile"
       system "sed -i '7iXZ_SUPPORT = 1' Makefile"
+      system "sed -i '8iZSTD_SUPPORT = 1' Makefile"
       system 'make'
     end
   end
 
   def self.install
```
Comment (Zopolis4) [inline packages/squashfs.rb:45]: From a quick glance at the repo, it looks like it has support for installing via the makefile (make install). Is there a reason why we don't do that?

Comment (satmandu) [reply packages/squashfs.rb:45]: Good question...

Comment (satmandu) [reply packages/squashfs.rb:52]: Rebuilt this using `make install`...

**Review by Zopolis4 — APPROVED** [review]
Having to set things manually in the makefile with sed feels a little ugly, but that's just the way it is I suppose, at least until the CMake PR is merged.

**Comment by Zopolis4** [comment]
Linking in plougher/squashfs-tools#261 so I don't forget
