### PR TITLE
Mpv => 0.37

### LINKED ISSUE #9268: 🐞 Bug Mpv is not working
**Describe the bug**
mpv fails to start due to missing library (libspirv.so.14)
**To Reproduce**

1. I executed this command:

      ```shell
      mpv
      ```

      Output:

      ```
      # output of your command](mpv: error while loading shared libraries: libSPIRV.so.14: cannot open shared object file: No such file or directory)
      ```

**Expected behavior**
mpv should open normally

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.42.7`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 45fb71cf1 `Add arpscan package (#9266) (4 hours ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R120-15662.88.0`
- OS channel: `stable-channel`

</details>
Crew is exiting.
***

**Additional context**

What I think needs to be done:

      - [ ] step one
      - [ ] step two

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #9268

- mpv => 0.37
- Add libplacebo
- Add libdovi

Works properly:
- [x] `x86_64`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=mpv crew update
```
image

### CODE REVIEW

**Review by uberhacker — APPROVED** [review]

File: packages/libdovi.rb [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+  depends_on 'cargo_c' => :build
+  depends_on 'fontconfig' => :build
+  depends_on 'gcc_lib' # R
+  depends_on 'glibc' # R
+  depends_on 'rust' => :build
+
+  def self.build
+    Dir.chdir('dolby_vision') do
+      system "#{ARCH == 'x86_64' ? 'RUSTFLAGS="-C target-cpu=x86-64-v3"' : ''} cargo build --release"
```
Comment (Zopolis4) [inline packages/libdovi.rb:30]: Do all chromebooks support x86-84-v3?

Comment (satmandu) [reply packages/libdovi.rb:30]: It's only used by `mpv`, which requires a current Chromebook with current glibc, so for those purposes, yes.
