### PR TITLE
freerdp => 2.8.1

### LINKED ISSUE #7576: sommelier doesn't work properly on lenovo chromebook duet
## Description

After installing `sommelier` with chromebrew,  all GUI apps don't launch with the error `cannot open display`. I was trying to install `remmina` with the command,

`crew install remmina`

before launching remmina, I wanted to ensure if sommelier is working properly. so, I ran `restartsommelier` before launching remmina. but it gives the output, 

```
some sommelier processes failed to start
sommelier processes running:  
 
/usr/local/bin/startsommelier: line 39: return: can only `return' from a function or sourced script
```
and when I try to launch `remmina` with `G_MESSAGES_DEBUG=all`, my output was

```
** (process:26382): DEBUG: 23:26:28.707: (remmina_pref_init) - periodic_rmnews_last_get set to 0
** (process:26382): DEBUG: 23:26:28.715: (remmina_file_manager_init) - Initialized the "/usr/local/.config/.local/share/remmina" data folder
(process:26382): GLib-GIO-DEBUG: 23:26:28.720: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
Load modules from /usr/local/lib/remmina/plugins
Remmina plugin glibsecret (type=Secret) has been registered, but is not yet initialized/activated. The initialization order is 2000.
** (process:26382): DEBUG: 23:26:28.862: (remmina_plugin_entry) - gfx_h264_available: 1
** (process:26382): DEBUG: 23:26:28.863: (remmina_rdp_settings_kbd_init) - rdp_keyboard_remapping_list: (null)
xprop:  unable to open display ':0'
xprop:  unable to open display ':0'
Failed to load plugin: /usr/local/lib/remmina/plugins/remmina-plugin-vnc.so.
Error: /usr/local/lib/libjpeg.so.9: version `LIBJPEG_8.0' not found (required by /usr/local/lib/libvncclient.so.1)
(process:26382): GLib-GIO-DEBUG: 23:26:28.877: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)

(process:26382): libsecret-CRITICAL **: 23:26:28.881: secret_service_load_collections_sync: assertion 'paths != NULL' failed
[glibsecret] unable to get secret service: Unknown error.
(process:26382): GLib-DEBUG: 23:26:28.882: unsetenv() is not thread-safe and should not be used after threads are created
(org.remmina.Remmina:26382): GLib-GIO-DEBUG: 23:26:28.883: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)

(org.remmina.Remmina:26382): Gtk-WARNING **: 23:26:28.886: cannot open display: :0
```
I have double checked my display variable. it is set to :0. 

Attempting to launch remmina with,

`sommelier -X --x-display=$DISPLAY --scale=1 remmina`

gives a different error, 

`error: failed to create virtwl context: Inappropriate ioctl for device`

I have tried reinstalling `remmina` with the `-s` option. It didn't change anything.
## Versions and system information

***
Output of `crew sysinfo`

```
/usr/local/bin/crew:1820:in `sysinfo_command': uninitialized constant ARCH_ACTUAL (NameError)

    - Architecture: `#{ARCH_ACTUAL}` (`#{ARCH}`)
                       ^^^^^^^^^^^
        from /usr/local/bin/crew:1867:in `<main>'
```
Output of `cat /etc/lsb-release`

```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=9138510
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={50F3C95B-CA5B-4AF8-87A2-8CD19588BD12}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={50F3C95B-CA5B-4AF8-87A2-8CD19588BD12}
CHROMEOS_RELEASE_BOARD=kukui-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=87
CHROMEOS_RELEASE_BUILDER_PATH=kukui-release/R107-15117.87.0
CHROMEOS_RELEASE_BUILD_NUMBER=15117
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=107
CHROMEOS_RELEASE_DESCRIPTION=15117.87.0 (Official Build) stable-channel kukui 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=15117.87.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=15117.87.0
```
***

Any help is much appreciated. Thanks !

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #7576 (Fixes libjpeg version issue with remmina.) This may not fix the rest of the issue.

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=freerdp CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/freerdp.rb [hunk 1]
```diff
@@ -3,41 +3,65 @@
...
+  depends_on 'pulseaudio' => :build
   depends_on 'sommelier'
+  depends_on 'wayland' => :build
+  depends_on 'xdg_base'
+  depends_on 'xmlto' => :build
+  depends_on 'xprop' => :build
 
   def self.build
-    Dir.mkdir 'builddir'
+    FileUtils.mkdir_p 'builddir'
```
Comment (uberhacker) [inline packages/freerdp.rb:64]: The `_p` is not necessary.  This is only one directory level. :)

**Review by uberhacker — APPROVED** [review]
