### PR TITLE
Balena Etcher => 1.18.6

### LINKED ISSUE #8114: 🐞 Balena Etcher is broken
```
chronos@localhost /usr/local/lib/crew/packages ((a26da87...) %|SPARSE)$ balena-etcher 
[1307:0324/180757.976364:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180757.987208:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180757.994741:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180757.997117:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180757.999435:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180758.000750:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180758.002138:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180758.003356:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180758.004372:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
[1307:0324/180758.004407:FATAL:gpu_data_manager_impl_private.cc(450)] GPU process isn't usable. Goodbye.
/usr/local/bin/balena-etcher: line 10:  1307 Trace/breakpoint trap   (core dumped) "${script_dir}"/balena-etcher.bin "$@"
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #8114

- Add back wrapper script.

Works properly:
- [x] `x86_64`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=balena CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/balena_etcher.rb [hunk 1]
```diff
@@ -31,9 +31,26 @@ class Balena_etcher < Package
...
 
+  def self.build
+    @etcher = <<~EOF
+      #!/bin/bash
+      xhost si:localuser:root
+      cd #{CREW_PREFIX}/share/balena-etcher
+      sudo -E LD_LIBRARY_PATH=#{CREW_LIB_PREFIX} ./AppRun "$@"
+    EOF
+    File.write('etcher.sh', @etcher)
+  end
```
Comment (uberhacker) [inline packages/balena_etcher.rb:42]: Good call.  I knew there was a reason why we needed this.

**Review by uberhacker — APPROVED** [review]
