### PR TITLE
Adwaita_icon_theme 40.1.1 => 42.0

### LINKED ISSUE #7152: [adwaita_icon_theme] Unable to build from source
```
$ crew reinstall adwaita_icon_theme -s
... snip ...
Can't load file: Unrecognized image file format
Can't load file: Unrecognized image file format
Can't load file: Unrecognized image file format
make[3]: *** [Makefile:448: install-data-local] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/adwaita_icon_theme.20220619013908.dir/adwaita-icon-theme-40.1.1/src/symbolic'
make[2]: *** [Makefile:314: install-am] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/adwaita_icon_theme.20220619013908.dir/adwaita-icon-theme-40.1.1/src/symbolic'
make[1]: *** [Makefile:324: install-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/adwaita_icon_theme.20220619013908.dir/adwaita-icon-theme-40.1.1/src'
make: *** [Makefile:536: install-recursive] Error 1
/usr/local/lib/crew/lib/package.rb:259:in `system': Command failed with exit 2: bash
adwaita_icon_theme failed to install: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " LDFLAGS="-flto " bash -c make -j8 install DESTDIR=/usr/local/tmp/crew/dest` exited with 2
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #7152.

### CODE REVIEW

File: packages/adwaita_icon_theme.rb [hunk 1]
```diff
@@ -3,25 +3,27 @@
...
-       i686: 'c4f97fc424e02d37498be3e27237acd41f0051c101dec307c5635c07969461a9',
-     x86_64: 'a900ebcf4874828df3891c23921154aa1681ba6690f951fbf75358f88f0ad458'
+    aarch64: 'c6dd539659f98a4f83247943715aef136002aa590c4e6e558c89762c60fafefc',
+     armv7l: 'c6dd539659f98a4f83247943715aef136002aa590c4e6e558c89762c60fafefc',
+       i686: 'f13d05ff2696a2fd7488a7dc4e4e78ad98fe8d7bcf1d63c314e533610a071b6d',
+     x86_64: '862aa3d398d4891c8f6923d6c9c2283ebfa9438647a1a25e9172532433db52fb',
   })
 
+  no_patchelf
+
```
Comment (satmandu) [inline packages/adwaita_icon_theme.rb:26]: Also needs the `gnome` flag.

**Review by satmandu — CHANGES_REQUESTED** [review]
Just needs the gnome flag added.

File: packages/adwaita_icon_theme.rb (hunk 1 above)
Comment (uberhacker) [reply packages/adwaita_icon_theme.rb:26]: Done.

**Review by satmandu — APPROVED** [review]

**Review by supechicken — APPROVED** [review]
