### PR TITLE
Fix removing packages

### LINKED ISSUE #9770: crew remove does not remove files
image

Probably due to the busted `pkg.is_fake` check in `commands/remove.rb`.

<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `true`

- Chromebrew version: `1.47.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 1efb8808b `mesa => 24.0.7 (#9767) (81 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `nocturne-release/R123-15786.48.0`
- OS channel: `stable-channel`

</details>

### PR DESCRIPTION
**Pull request by Zopolis4**
Fixes #9770

Tested and working on `x86_64`.

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=ohadnta crew update
```

### CODE REVIEW

**Comment by Zopolis4** [comment]
If anyone has removed any packages in the last 14 hours, the files will still be there but they will be marked as not installed in the `device.json`-- given the extremely short lifespan of the bug the best solution is just for people to install and then remove those packages if need be.

**Review by satmandu — APPROVED** [review]

File: commands/remove.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ def self.remove(pkg, verbose)
     pkg.preremove
 
     # Remove the files and directories installed by the package.
-    unless pkg.is_fake
+    unless pkg.is_fake?
```
Comment (uberhacker) [inline commands/remove.rb:26]: Good call!
