### PR TITLE
Update wayland_protocols, fix wayland_info compat, have crew identify incompatible packages when throwing incompatibility error

### LINKED ISSUE #9750: 🐞 Bug "some sommelier processes failed to start"
**Describe the bug**

some sommelier processes failed to start

**To Reproduce**

Environment
ASUS L202S
terra 97.0.4692.77 https://chrome100.dev/board/terra/
brunch_r97_stable_20220121 https://github.com/sebanc/brunch

```
$ brew install sommelier
...
wayland-info: /usr/local/lib64/libc.so.6: version `GLIBC_2.34' not found (required by wayland-info)
wayland-info: /usr/local/lib64/libc.so.6: version `GLIBC_2.34' not found (required by wayland-info)
Sommelier SCALE is set to 1.
SCALE may be manually set in ~/.sommelier.env .
[1]+  Exit 1                  crew install sommelier
some sommelier processes failed to start
```

```
$ readlink -f '/sys/class/drm/renderD129/device/driver'
(no output)
$ readlink -f '/sys/class/drm/renderD128/device/driver'
/sys/bus/pci/drivers/i915
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #9750

- Update `wayland_protocols`, and change compat to `all`.
- Fix `glibc` compat of `wayland_info` by building on an older container.
- Have `crew` identify incompatible packages when throwing incompatibility error.
- Add `is_fake` package alias from `wayland_utils` to `wayland_info`.

Builds properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=wayland_info crew update
```

### CODE REVIEW

File: packages/wayland_utils.rb [hunk 1]
```diff
@@ -1,21 +1,20 @@
 require 'buildsystems/meson'
 
-class Wayland_info < Meson
+class Wayland_utils < Meson
   description 'wayland-info is a utility for displaying information about the Wayland protocols supported by a Wayland compositor.'
```
Comment (Zopolis4) [inline packages/wayland_utils.rb:4]: Update description?

Comment (satmandu) [reply packages/wayland_utils.rb:4]: `wayland-info` is actually the ONLY binary provided by the `wayland_utils` package, so we don't need to update the description.
```
cat manifest/x86_64/w/wayland_utils.filelist
/usr/local/bin/wayland-info
/usr/local/share/man/man1/wayland-info.1.zst
```

Comment (uberhacker) [reply packages/wayland_utils.rb:4]: Rename the package?
