### PR TITLE
wine => 8.0, new packages faudio, opencl-headers, opencl-icd-loader and vkd3d

### LINKED ISSUE #7667: wine and minecraft dont work🐞 Bug
hello all! so my current issue is that  when running wincfg i all i get is failing to create a file to dir

i have searched for ways to fix this but i when using wine on crositi or whatever i used it perfectly 
https://pastebin.com/fDM1GQBf

i also cant use minecraft as it just gives me nothing after clicking PLAY. i could use lutris with it on the other linux and would launch fine.
`chronos@localhost / $ 
chronos@localhost / $ minecraft-launcher
https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
[1122/205307.928156:INFO:main_context.cpp(130)] CEF initialized successfully.
[1122/205307.928314:INFO:main_context.cpp(132)] CEF version: 99.2.14+g3f796b8+chromium-99.0.4844.84
sh: 1: orca: not found
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
Created browser window for reuse: 0x400002
[1122/205308.533005:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[1122/205310.846881:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Created browser window for reuse: 0x400008
[1122/205338.650350:INFO:LauncherAppRenderer.cpp(542)] OnContextReleased: no frame (unknown context), browser id=2
[1122/205344.420169:INFO:LauncherAppRenderer.cpp(542)] OnContextReleased: no frame (unknown context), browser id=2
[1122/205353.730754:INFO:LauncherAppRenderer.cpp(542)] OnContextReleased: no frame (unknown context), browser id=2
[1122/205353.850063:INFO:LauncherAppRenderer.cpp(542)] OnContextReleased: no frame (unknown context), browser id=2
[1122/205353.966976:WARNING:connection.cc(61)] X error received.  Request: DestroyWindowRequest, Error: WindowError{.sequence = 1165, .bad_value = 4194313, .minor_opcode = 0, .major_opcode = 4}
Created browser window for reuse: 0x40000a
[1122/205402.234896:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[1122/205406.651356:INFO:LauncherAppRenderer.cpp(52)] [Info: 2022-11-23 01:53:07.586675634: LauncherMain.cpp(112)] Initiated models
[1122/205406.666819:INFO:LauncherAppRenderer.cpp(52)] [Info: 2022-11-23 01:53:07.594964977: LauncherController.cpp(578)] Constructing launcher controller with workDir: /.../.minecraft, isActive: 0
[1122/205406.667836:INFO:LauncherAppRenderer.cpp(52)] [Info: 2022-11-23 01:53:55.999300379: LauncherAppRenderer.cpp(173)] Javascript bridge extended in OnWebKitInitialized.
[1122/205407.020408:INFO:LauncherAppRenderer.cpp(542)] OnContextReleased: no frame (unknown context), browser id=3
[1122/205407.122779:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[1122/205407.108926:INFO:LauncherAppRenderer.cpp(70)] OnBrowserDestroyed: id=3
[1122/205423.580924:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
[1122/205423.645878:ERROR:gpu_process_host.cc(972)] GPU process exited unexpectedly: exit_code=512
[1122/205423.645983:WARNING:gpu_process_host.cc(1277)] The GPU process has crashed 1 time(s)
[1122/205423.727699:WARNING:connection.cc(61)] X error received.  Request: DestroyWindowRequest, Error: WindowError{.sequence = 1587, .bad_value = 4194315, .minor_opcode = 0, .major_opcode = 4}
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
[1122/205423.921983:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[1122/205423.935102:WARNING:gpu_process_host.cc(1000)] Reinitialized the GPU process after a crash. The reported initialization time was 253 ms
[1122/205423.991762:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1122/205428.565837:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[1122/205435.367416:WARNING:connection.cc(61)] X error received.  Request: DestroyWindowRequest, Error: WindowError{.sequence = 1807, .bad_value = 4194307, .minor_opcode = 0, .major_opcode = 4}
`

details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.28.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 7a2cb8e `libsdl2 -> 2.26.0 (#7666) (7 hours ago)`

- OS variant: `Chrome OS`
- OS version: `coral-release/R107-15117.111.0`
- OS channel: `stable-channel`

</details>

### PR DESCRIPTION
**Pull request by saltedcoffii**
Fixes #7667 #6128 #6858 (Some of these in part)
wine => 8.0
faudio - something to do with windows audio i think?
opencl - i don't know but wine was failing without it
vkd3d - a directx 12 implementation

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/saltedcoffii/chromebrew.git CREW_TESTING_BRANCH=wine_7.1 CREW_TESTING=1 crew update
```

### CODE REVIEW

File: lib/const.rb [hunk 1]
```diff
@@ -34,6 +35,7 @@
 CREW_DEST_DIR = CREW_BREW_DIR + 'dest'
 CREW_DEST_PREFIX = CREW_DEST_DIR + CREW_PREFIX
 CREW_DEST_LIB_PREFIX = CREW_DEST_DIR + CREW_LIB_PREFIX
+CREW_DEST_DLL_PREFIX = CREW_DEST_PREFIX + CREW_DLL_PREFIX
```
Comment (supechicken) [inline lib/const.rb:38]: If a variable is used in one package only, it should not be included in `const.rb`.

File: packages/mesa.rb [hunk 2]
```diff
@@ -17,10 +17,10 @@ class Mesa < Package
...
   binary_sha256({
-    aarch64: 'ab9a19dd501715367d45e843b64b2aec16741538caa033f61133d9e78eca68df',
-     armv7l: 'ab9a19dd501715367d45e843b64b2aec16741538caa033f61133d9e78eca68df',
-       i686: '9d70ca4db18e06c3d63f867801171e3fc960b841a9e62218ce3ff91b3036bd63',
-     x86_64: 'bf3dff20994cdd88a1a242351c21bea4ce111410171ea5d39728fd6406ea40bf'
+    aarch64: '5e018f58ac7261a46c8e6e133f26efa3e20d3daa7321584c70b1fdc4be6c9c71',
+     armv7l: '5e018f58ac7261a46c8e6e133f26efa3e20d3daa7321584c70b1fdc4be6c9c71',
+       i686: 'f67e9f749982cf67ca6942d0ec25d9b623ecfb687434e89d178edc2f05234b0c',
+     x86_64: '05cf28be056481799ea5458fdb050f33c5410ccf3e8ffc63b0dee02cdafef450'
   })
```
Comment (uberhacker) [inline packages/mesa.rb:24]: Should we add tests with `def self.check`?

File: packages/opencl_icd_loader.rb [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+        cmake -G Ninja \
+        #{CREW_CMAKE_OPTIONS} \
+        -DOPENCL_HEADERS_INSTALL_DIR=#{CREW_PREFIX} .."
+    end
+    system 'samu -C builddir'
+  end
+
+  def self.install
+    system "DESTDIR=#{CREW_DEST_DIR} samu -C builddir install"
+  end
```
Comment (uberhacker) [inline packages/opencl_icd_loader.rb:41]: Add `def self.check` section?

File: packages/vkd3d.rb [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+  def self.build
+    system "#{CREW_ENV_FNO_LTO_OPTIONS} ./configure #{CREW_OPTIONS} \
+            --with-xcb \
+            --with-spirv-tools"
+    system 'make'
+  end
+
+  def self.install
+    system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
+  end
```
Comment (uberhacker) [inline packages/vkd3d.rb:40]: Add `def self.check` section?

File: packages/opencl_icd_loader.rb [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+       i686: '53e3402e0df4c65cb9d6169ffbd96508888b1419d6626ea648f8e7e292dd70a0',
+     x86_64: 'e2d9de8e96da760c71576e88a0af5132b052abf070b8c698aac6e2e2fe5929b9'
+  })
+
+  depends_on 'opencl_headers' => :build
+
+  def self.build
+    Dir.mkdir 'builddir'
+    Dir.chdir 'builddir' do
+      system "env #{CREW_ENV_OPTIONS} \
```
Comment (supechicken) [inline packages/opencl_icd_loader.rb:31]: `system CREW_ENV_OPTIONS_HASH, "cmake -G Ninja \\`?

File: packages/wine.rb [hunk 6]
```diff
@@ -108,9 +111,9 @@ def self.remove
...
       when 'y', 'Y'
         FileUtils.rm_rf config_dir
-        puts "#{config_dir} removed.".lightred
+        puts "#{config_dir} removed.".lightgreen
       else
-        puts "#{config_dir} saved.".lightgreen
+        puts "#{config_dir} saved.".lightblue
       end
     end
   end
```
Comment (uberhacker) [inline packages/wine.rb:119]: Add `def self.check` section?

File: packages/opencl_headers.rb [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+    Dir.chdir 'builddir' do
+      system "cmake -G Ninja \
+        #{CREW_CMAKE_OPTIONS} .."
+    end
+    system 'samu -C builddir'
+  end
+
+  def self.install
+    system "DESTDIR=#{CREW_DEST_DIR} samu -C builddir install"
+  end
```
Comment (uberhacker) [inline packages/opencl_headers.rb:37]: Add `def self.check` section?

File: lib/const.rb [hunk 8]
```diff
@@ -25,6 +25,7 @@
 end
 
 CREW_LIB_PREFIX = CREW_PREFIX + '/' + ARCH_LIB
+CREW_DLL_PREFIX = CREW_LIB_PREFIX + '/wine'
```
[the remark this answers is not in the document]
Comment (saltedcoffii) [reply lib/const.rb:28]: This prefix is specifically for wine DLLs, WINEPREFIX is a completely different thing pointing to "~/.wine" by default.

File: packages/wine.rb [hunk 9]
```diff
@@ -108,9 +111,9 @@ def self.remove
       case $stdin.getc
       when 'y', 'Y'
         FileUtils.rm_rf config_dir
-        puts "#{config_dir} removed.".lightred
+        puts "#{config_dir} removed.".lightgreen
       else
-        puts "#{config_dir} saved.".lightgreen
+        puts "#{config_dir} saved.".lightblue
```
[the remark this answers is not in the document]
Comment (saltedcoffii) [reply packages/wine.rb:116]: Green is for success, blue is for information, right?

File: lib/const.rb (hunk 1 above)
Comment (saltedcoffii) [reply lib/const.rb:38]: it will be included in other packages later on, e.g., wine-mono and wine-gecko when I made them

File: packages/wine.rb (hunk 6 above)
Comment (saltedcoffii) [reply packages/wine.rb:119]: I'd love to, when we get it to built first

File: packages/opencl_headers.rb (hunk 7 above)
Comment (saltedcoffii) [reply packages/opencl_headers.rb:37]: there aren't any checks to make

File: packages/vkd3d.rb (hunk 4 above)
Comment (saltedcoffii) [reply packages/vkd3d.rb:40]: tests were succeeding on i686 but failing on x86_64

File: packages/opencl_icd_loader.rb (hunk 3 above)
Comment (saltedcoffii) [reply packages/opencl_icd_loader.rb:41]: good idea

File: packages/mesa.rb (hunk 2 above)
Comment (saltedcoffii) [reply packages/mesa.rb:24]: yes probably

File: lib/const.rb (hunk 1 above)
Comment (satmandu) [reply lib/const.rb:38]: maybe we should add a `wine.rb` for wine specific variables?

**Comment by satmandu** [comment]
osmesa requires building mesa with `-Dosmesa=true`

**Comment by satmandu** [comment]
(Added osmesa to the current mesa build...)

File: lib/const.rb (hunk 1 above)
Comment (uberhacker) [reply lib/const.rb:38]: It's fine to add to const.rb.  I don't want to get too complicated where it becomes difficult to figure out what to do with specific packages.

File: packages/vkd3d.rb (hunk 4 above)
Comment (uberhacker) [reply packages/vkd3d.rb:40]: Drat, I was hoping it would be the other way around.

**Comment by satmandu** [comment]
osmesa should now be in https://github.com/skycocker/chromebrew/pull/6700

```
Message: Configuration summary:
        
        prefix:          /usr/local
        libdir:          lib64
        includedir:      include
        
        OpenGL:          yes (ES1: yes ES2: yes)
        
        OSMesa:          libOSMesa
        
        DRI platform:    drm
        DRI drivers:     i915 i965 r100 r200 nouveau
        DRI driver dir:  /usr/local/lib64/dri
        
        GLX:             DRI-based
        
        EGL:             yes
        EGL drivers:     builtin:egl_dri2 builtin:egl_dri3
        EGL/Vulkan/VL platforms:   x11 wayland surfaceless drm
        GBM:             yes
        GBM backends path: /usr/local/lib64/gbm
        
        Vulkan drivers:  amd intel swrast
        Vulkan ICD dir:  share/vulkan/icd.d
        
        llvm:            yes
        llvm-version:    13.0.1
        
        Gallium drivers: r300 r600 radeonsi nouveau virgl svga swrast iris crocus
        Gallium st:      mesa xa xvmc vdpau
        HUD lmsensors:   yes
        
        Shared-glapi:    yes
        
        Perfetto:        no
        Perfetto ds:     auto
```

File: packages/mesa.rb (hunk 2 above)
Comment (uberhacker) [reply packages/mesa.rb:24]: New binaries needed because of #6700?

Comment (satmandu) [reply packages/mesa.rb:24]: Or just use the binaries in https://github.com/skycocker/chromebrew/pull/6700 since it has the libosmesa wine needs anyways...

File: packages/opencl_icd_loader.rb (hunk 5 above)
Comment (satmandu) [reply packages/opencl_icd_loader.rb:31]: Do we need CREW_ENV_OPTIONS any more? Isn't that added automatically?

Comment (supechicken) [reply packages/opencl_icd_loader.rb:31]: Yeah I didn't realize that :)

**Comment by satmandu** [comment]
And there is wine 7.2 now!

**Comment by JakoDel** [comment]
Patiently waiting for missing packages to be included :)
Thanks a lot for your work guys! My development skills arent nearly enough to do some actual work but If there's something I can help with such as.. idfk debugging or trying to compile some stuff from source let me know

**Comment by satmandu** [comment]
> Patiently waiting for missing packages to be included :) Thanks a lot for your work guys! My development skills arent nearly enough to do some actual work but If there's something I can help with such as.. idfk debugging or to compiling some stuff from source and see if it works let me know

Interested in joining the slack @JakoDel ?  @uberhacker here's a potential helper...

**Comment by saltedcoffii** [comment]
ooo yess more helpers we need more of those

**Comment by JakoDel** [comment]
@satmandu sorry for the delay, don't check github notifications too often.
not sure what you mean with slack (if like the literal term or Slack lol) but yeah I'd love to!

**Comment by uberhacker** [comment]
@JakoDel: If you would like to join our Slack channel, please email your request to crewonslack@gmail.com and I can send back an invite link.

**Comment by satmandu** [comment]
@saltedcoffii maybe see if 7.5 builds?

**Comment by satmandu** [comment]
I built an updated vkd3d, but @saltedcoffii maybe see if tests work on this?

Also, tests on libfaudio don't seem to work in a container, which is why there are no new binaries for that.

Might make sense to wait on a wine build until https://github.com/skycocker/chromebrew/pull/6938 is finished, as there are many deps inside there. (But that's waiting on some work from @supechicken ... so I can reconcile his approach with mine.)

**Comment by uberhacker** [comment]
I attempted to build this on x86_64 and received the output below:
```
x86_64-cros-linux-gnu-gcc -m64 -c -o dlls/wldap32/dn.o ../dlls/wldap32/dn.c -Idlls/wldap32 -I../dlls/wldap32 -Iinclude -I../include \
  -D__WINESRC__ -D_REENTRANT -fPIC -fasynchronous-unwind-tables -Wall -pipe -fcf-protection=none \
  -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Winit-self -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes \
  -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op \
  -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold 
In file included from ../dlls/wldap32/add.c:33:
../dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
      |             ^~~~~~~~~~~~
In file included from ../dlls/wldap32/add.c:26:
/usr/local/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
In file included from ../dlls/wldap32/ber.c:30:
../dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
      |             ^~~~~~~~~~~~
In file included from ../dlls/wldap32/ber.c:25:
/usr/local/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
make: *** [Makefile:152144: dlls/wldap32/add.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:152158: dlls/wldap32/ber.o] Error 1
In file included from ../dlls/wldap32/control.c:33:
../dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
      |             ^~~~~~~~~~~~
In file included from ../dlls/wldap32/control.c:26:
/usr/local/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
In file included from ../dlls/wldap32/compare.c:33:
../dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
      |             ^~~~~~~~~~~~
In file included from ../dlls/wldap32/compare.c:26:
/usr/local/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
In file included from ../dlls/wldap32/delete.c:33:
../dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
      |             ^~~~~~~~~~~~
In file included from ../dlls/wldap32/delete.c:26:
/usr/local/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
make: *** [Makefile:152215: dlls/wldap32/control.o] Error 1
make: *** [Makefile:152200: dlls/wldap32/compare.o] Error 1
make: *** [Makefile:152230: dlls/wldap32/delete.o] Error 1
In file included from ../dlls/wldap32/dn.c:33:
../dlls/wldap32/winldap_private.h:323:13: error: conflicting types for ‘ldap_connect’; have ‘ULONG(WLDAP32_LDAP *, LDAP_TIMEVAL *)’ {aka ‘unsigned int(struct wldap32 *, struct l_timeval *)’}
  323 | ULONG CDECL ldap_connect(WLDAP32_LDAP*,LDAP_TIMEVAL*);
      |             ^~~~~~~~~~~~
In file included from ../dlls/wldap32/dn.c:26:
/usr/local/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
make: *** [Makefile:152245: dlls/wldap32/dn.o] Error 1
/usr/local/lib/crew/lib/package.rb:258:in `system': Command failed with exit 2: bash
wine failed to build: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " LDFLAGS="-flto " bash -c make -j8` exited with 2
```

**Comment by satmandu** [comment]
merged master and updated wine to 7.7...

**Comment by satmandu** [comment]
This is what I see with wine 7.7 on `x86_64`:
```
programs/winetest/wmadmod_test.res programs/winetest/wmiutils_test.res \
  programs/winetest/wmp_test.res programs/winetest/wmvcore_test.res programs/winetest/wpc_test.res \                                        programs/winetest/ws2_32_test.res programs/winetest/wsdapi_test.res \                                                                     programs/winetest/wshom.ocx_test.res programs/winetest/wsnmp32_test.res \                                                                 programs/winetest/wtsapi32_test.res programs/winetest/xactengine3_7_test.res \                                                            programs/winetest/xaudio2_7_test.res programs/winetest/xinput1_3_test.res \                                                               programs/winetest/xmllite_test.res programs/winetest/cmd.exe_test.res \                                                                   programs/winetest/conhost.exe_test.res programs/winetest/find.exe_test.res \
  programs/winetest/fsutil.exe_test.res programs/winetest/reg.exe_test.res \                                                                programs/winetest/regedit.exe_test.res programs/winetest/schtasks.exe_test.res \                                                          programs/winetest/services.exe_test.res programs/winetest/wscript.exe_test.res \                                                          programs/winetest/xcopy.exe_test.res dlls/ole32/libole32.cross.a libs/uuid/libuuid.cross.a \                                              dlls/comctl32/libcomctl32.cross.a dlls/version/libversion.cross.a dlls/user32/libuser32.cross.a \
  dlls/gdi32/libgdi32.cross.a dlls/advapi32/libadvapi32.cross.a dlls/wsock32/libwsock32.cross.a \                                           dlls/winecrt0/libwinecrt0.cross.a dlls/msvcrt/libmsvcrt.cross.a dlls/kernel32/libkernel32.cross.a \                                       dlls/ntdll/libntdll.cross.a -Wl,-delayload,ole32.dll               Wine build complete.                                                 make: *** No targets specified and no makefile found.  Stop.         wine failed to build: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " LDFLAGS="-flto " bash -c make -j4` exited with 2               /usr/local/lib/crew/lib/package.rb:258:in `system': Command failed with exit 2: bash
```

Maybe the build commands need updating?

**Comment by satmandu** [comment]
This needs to have master merged...

**Comment by satmandu** [comment]
This is the error I get with 7.8:
```
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/msvcr90/libmsvcr90.cross.a --export ../dlls/msvcr90/msvcr90.spec \
  dlls/msvcr90/iob.cross.o dlls/msvcr90/mathf.cross.o dlls/msvcr90/onexit.cross.o \
  dlls/msvcr90/sincos.cross.o
bison -o dlls/msxml3/xslpattern.tab.c ../dlls/msxml3/xslpattern.y
clang -c -o dlls/msxml3/xslpattern.yy.cross.o dlls/msxml3/xslpattern.yy.c -Idlls/msxml3 -I../dlls/msxml3 -Iinclude \
  -I../include -I../include/msvcrt -I../libs/xslt -I../libs/xml2/include -D__WINESRC__ \
  -DLIBXSLT_STATIC -DLIBXML_STATIC -D_UCRT -D__WINE_PE_BUILD -Wall -target x86_64-windows \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Winit-self \
  -Wno-pragma-pack -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wabsolute-value -Wno-format -Wnonnull -mcx16 -gdwarf-4 -Wformat \
  -g -O2
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/ncrypt/libncrypt.cross.a --export ../dlls/ncrypt/ncrypt.spec
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/ninput/libninput.cross.a --export ../dlls/ninput/ninput.spec
tools/winegcc/winegcc -o dlls/normaliz/normaliz.dll --wine-objdir . -b x86_64-windows --lib-suffix=.cross.a \
  -Wl,--wine-builtin -shared ../dlls/normaliz/normaliz.spec -Wb,--data-only -mno-cygwin \
  
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/mshtml/libmshtml.cross.a --export ../dlls/mshtml/mshtml.spec
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/ntdsapi/libntdsapi.cross.a --export ../dlls/ntdsapi/ntdsapi.spec
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/netio.sys/libnetio.cross.a --export \
  ../dlls/netio.sys/netio.sys.spec
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/oleacc/liboleacc.cross.a --export ../dlls/oleacc/oleacc.spec
tools/winebuild/winebuild -b x86_64-windows -w --implib -o dlls/oledlg/liboledlg.cross.a --export ../dlls/oledlg/oledlg.spec
tools/winebuild/winebuild -w --implib -o dlls/kernel32/libkernel32.a -m64 --export ../dlls/kernel32/kernel32.spec
tools/winebuild/winebuild -w --implib -o dlls/ntdll/libntdll.a -m64 --export ../dlls/ntdll/ntdll.spec
tools/winegcc/winegcc -o dlls/openal32/openal32.dll --wine-objdir . -m64 -fPIC -fasynchronous-unwind-tables \
  -Wb,--fake-module -shared ../dlls/openal32/openal32.spec -Wb,--prefer-native -mcygwin
tools/winebuild/winebuild -w --implib -o dlls/glu32/libglu32.a -m64 --export ../dlls/glu32/glu32.spec
tools/winebuild/winebuild -w --implib -o dlls/user32/libuser32.a -m64 --export ../dlls/user32/user32.spec
tools/winebuild/winebuild -w --implib -o dlls/gdi32/libgdi32.a -m64 --export ../dlls/gdi32/gdi32.spec
winebuild: /usr/local/bin/as failed with status 127
make: *** [Makefile:58921: dlls/gdi32/libgdi32.a] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by satmandu** [comment]
deps updated and master merged, but the new packages have not yet been added to `packages.yaml`.

**Comment by satmandu** [comment]
Attempting to build wine 8.0...

**Comment by satmandu** [comment]
Also, wine 8 advantage:
```
WoW64 thunks are implemented for essentially all Unix libraries, enabling a 32-bit PE module to call a 64-bit Unix library. Once the remaining direct PE/Unix calls have been removed, this will make it fully possible to run 32-bit Windows applications without any 32-bit Unix library.
```

This should eventually allow wine to work fine without requiring the i686 libraries wine would otherwise require for compatibility.

File: packages/wine.rb (hunk 6 above)
Comment (satmandu) [reply packages/wine.rb:116]: done.

**Review by satmandu — APPROVED** [review]
I think this is ready to go...

**Review by uberhacker — APPROVED** [review]

**Review by uberhacker — APPROVED** [review]
