### PR TITLE
Fix sommelier bugs

### LINKED ISSUE #7891: 🐞 Sommelier failed to start - Assertion `!ctx->xdg_shell' failed
**Description**
When I type `shell` in the crosh terminal of my chromebook, I get:
```shell
crosh> shell
Sommelier can use direct scaling.
some sommelier processes failed to start
```
If I type `cat /usr/local/var/log/sommelier.log` to see more detailed logs I get:
```shell
chronos@localhost / $ cat /usr/local/var/log/sommelier.log
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
(EE) could not connect to wayland server
```

**To Reproduce**
I enabled the developer mode on my chromebook .
I installed chromebrew from the crosh terminal.
I also installed sommelier with the `crew` command.
Then I reopened the crosh terminal and typed `shell`.

**Expected behavior**
Sommelier starts without printing an error log.

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`aarch64`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.30.8`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 11d8beb `gstreamer => 1.22.0 (#7863) (10 days ago)`

- OS variant: `Chrome OS`
- OS version: `strongbad-release/R109-15236.80.0`
- OS channel: `stable-channel`

</details>
***

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #7891 #7940 .  Please test on all architectures when you get a chance.  If this works for most testers, I will take out of draft and build binaries.

### Run the following to get these pull request changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/uberhacker/chromebrew.git CREW_TESTING_BRANCH=update-sommelier CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
We should also consider if a newer sommelier build fixes anything: https://chromium.googlesource.com/chromiumos/platform2.git/+log/HEAD/vm_tools/sommelier

**Review by satmandu — APPROVED** [review]
Works for me on `x86_64`...

**Comment by satmandu** [comment]
(FYI the most recent sommelier git tag doesn't work on x86_64 due to a complaint about missing zink... but I'm rebuilding mesa with that to see if it helps.)

**Comment by uberhacker** [comment]
The newer builds are what started to break everything spectacularly.  We need to make sure we have a version that works on as many platforms as possible; including older EOL ChromeOS versions; especially arm Chromebooks.  I'm guessing the newer builds don't have downward compatibility in mind and likely only work for x86_64.

File: packages/sommelier.rb [hunk 1]
```diff
@@ -393,22 +364,36 @@ def self.install
 
   def self.postinstall
     # all tasks are done by sommelier.env now
-    puts
-    puts 'Removing old sommelier env variable loading code in ~/.bashrc'.lightblue
-    system 'sed -i "/[sS]ommelier/d" -i.backup ~/.bashrc'
-    puts 'To complete the installation, execute the following:'.orange
-    puts 'source ~/.bashrc'.orange
+    now = `date +%Y%m%d%H%M`.chomp
```
Comment (supechicken) [inline packages/sommelier.rb:367]: Rubyize?
```ruby
now = Time.now.strftime('%Y%m%d%H%M')
```

File: packages/sommelier.rb [hunk 2]
```diff
@@ -393,22 +364,36 @@ def self.install
...
+    FileUtils.cp "#{HOME}/.bashrc", "#{HOME}/.bashrc.#{now}"
+    system "sed -i '/[sS]ommelier/d' #{HOME}/.bashrc"
+    diff = `diff #{HOME}/.bashrc #{HOME}/.bashrc.#{now}`.chomp
```
Comment (supechicken) [inline packages/sommelier.rb:370]: The previous command will fail if the file is not modified properly, extra checking is not needed

File: packages/sommelier.rb [hunk 3]
```diff
@@ -250,7 +232,7 @@ def self.build
           # some of these checks in an env.d file since we don't need
           # them run every time a shell is opened.
           # Get a list of all available DRM render nodes.
-          DRM_DEVICES_LIST=( /sys/class/drm/renderD* )
+          DRM_DEVICES_LIST=$(ls /dev/dri/renderD*)
```
Comment (supechicken) [inline packages/sommelier.rb:235]: The previous one is better? (and this change breaks line 251)

File: packages/sommelier.rb (hunk 2 above)
Comment (uberhacker) [reply packages/sommelier.rb:370]: The checking is there because the message is not needed if there are no changes.

File: packages/sommelier.rb (hunk 1 above)
Comment (uberhacker) [reply packages/sommelier.rb:367]: Good call.

File: packages/sommelier.rb (hunk 3 above)
Comment (uberhacker) [reply packages/sommelier.rb:235]: The previous check doesn't work and this does. :)

File: packages/sommelier.rb (hunk 1 above)
Comment (uberhacker) [reply packages/sommelier.rb]: Done.

**Comment by uberhacker** [comment]
@ncdm-stldr @gaslec: Does this update work on your arm Chromebooks?

**Comment by ncdm-stldr** [comment]
@uberhacker Yes it works on my chromebook.

(By the way, what is the proper way to test a chromebrew fork? I overwrote the sommelier.rb with the one from here. I suppose there is a better way?)

**Comment by uberhacker** [comment]
Thank you for testing @ncdm-stldr.  There are testing instructions at the top but the way you did it works too.  Just have to make sure the updated file is saved at `/usr/local/lib/crew/packages/sommelier.rb`.

**Comment by smartguy1196** [comment]
> The newer builds are what started to break everything spectacularly.  We need to make sure we have a version that works on as many platforms as possible; including older EOL ChromeOS versions; especially arm Chromebooks.  I'm guessing the newer builds don't have downward compatibility in mind and likely only work for x86_64.

Would you like me to test on a recent Zork board?

C13 Yoga Ryzen 3700c

**Comment by uberhacker** [comment]
> > The newer builds are what started to break everything spectacularly.  We need to make sure we have a version that works on as many platforms as possible; including older EOL ChromeOS versions; especially arm Chromebooks.  I'm guessing the newer builds don't have downward compatibility in mind and likely only work for x86_64.
> 
> Would you like me to test on a recent Zork board?
> 
> C13 Yoga Ryzen 3700c

Sure @smartguy1196, that would be great.

**Comment by smartguy1196** [comment]
Running it now. For record:

- Powerwashed on Version 110.0.5481.82 (Official Build) beta (64-bit)
  - rootfs-verification _is disabled_, however I've only made one change to the underlying system and that was to add a dbus policy for miraclecast (has no effect on system without miraclecast installed)

- Lenovo C13 Yoga - Ryzen 3700c - 16GB RAM

**Comment by satmandu** [comment]
@smartguy1196 I think I just fixed that missing `diffutils` dependency issue.

**Comment by smartguy1196** [comment]
Hmm... I'm getting the original error:

### I ran:
```bash
CREW_TESTING_REPO=https://github.com/uberhacker/chromebrew.git CREW_TESTING_BRANCH=update-sommelier CREW_TESTING=1 crew update
crew upgrade
crew reinstall sommelier
exit
shell
```
### output:
```
Sommelier can use direct scaling.
some sommelier processes failed to start
```
### `cat /usr/local/var/log/sommelier.log` output:
```
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
```

**Comment by smartguy1196** [comment]
Trying out the current chromebrew release for comparing.

1. Powerwashed Chromebook
2. Bash History:
```
sudo chromeos-setdevpasswd
sudo crossystem dev_boot_signed_only=1
curl -Ls git.io/vddgY | bash
curl -Ls git.io/vddgY | CREW_FORCE_INSTALL=1 bash
crew install sommelier
exit
shell - getting same errors as before
cat /usr/local/var/log/sommelier.log
```
3. Sommelier.log:
```
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
```

If I exit shell and restart it, this gets appended to sommelier.log:
```
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
```

So it seems like whatever issue that my Chromebook is having, it is independent of this one.

Since I don't see the other errors, I say that this PR is good.

**Comment by smartguy1196** [comment]
> pkill Xwayland ; restartsommelier

Trying that now (on the current release first, then I'll try this branch)

**Comment by smartguy1196** [comment]
Still same issue:

- Not powerwashed this time.
- Bash History:
```
CREW_TESTING_REPO=https://github.com/uberhacker/chromebrew.git CREW_TESTING_BRANCH=update-sommelier CREW_TESTING=1 crew update
crew upgrade
exit
shell - still same errors
pkill Xwayland ; restartsommelier
cat /usr/local/var/log/sommelier.log
```
**...no change**

but I do think that this issue may be rooted elsewhere, since I'm not getting all of the original errors from #7891. Just the one error

**Comment by smartguy1196** [comment]
Also, side note tried to install xterm for more thorough testing, and noticed a few dependencies are missing. May need to start an "Update Dependencies PR"

crew's xterm is missing the dependency packages: libxaw and libxinerama

was able to fix the xterm install by running:
```
crew install libxaw
crew install libxinerama
crew install xterm
```

Alright, now I'm off to do my classwork

**Comment by satmandu** [comment]
I've uploaded an entirely new revamped build fixing several bugs, please try this out. It works for me on x86_64 on nocturne/M109.

**Comment by satmandu** [comment]
> Also, side note tried to install xterm for more thorough testing, and noticed a few dependencies are missing. May need to start an "Update Dependencies PR"

I'm working on updating xterm... there's a build issue that I've taken upstream...

**Comment by satmandu** [comment]
@uberhacker @ncdm-stldr @smartguy1196 Any issues with this past build?

**Comment by smartguy1196** [comment]
> @uberhacker @ncdm-stldr @smartguy1196 Any issues with this past build?

I'll need until the weekend to run it again. I use my Chromebook for everything at the moment. Right now I need it to not be powerwashed, so that I work on my English Papers and Calc Homework

**Comment by ncdm-stldr** [comment]
> @uberhacker @ncdm-stldr @smartguy1196 Any issues with this past build?
It starts on my chromebook. It seems to work and I was able to launch  gnome-terminal.

However I find the following logs in `/usr/local/var/log/sommelier.log`:
```
Failed to initialize glamor, falling back to sw
(EE)
(EE) Backtrace:
(EE)
(EE) Segmentation fault at address 0x0
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
sommelier -X --x-display=:0 --scale=1 --direct-scale --glamor --force-drm-device=/dev/dri/rend>
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
~/.Xauthority: 1: ~/.Xauthority: Syntax error: Unterminated quoted string
Child exited with status: 2
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
```

**Comment by satmandu** [comment]
Thanks for that @ncdm-stldr. That just says that acceleration isn't working in sommelier. I'm not sure that ever worked for sommelier on arm? (Maybe due to the 32 bit userspace on the 64 bit kernel?)

**Comment by uberhacker** [comment]
Test results below:
- x86_64 - works
- armv7l - works
- aarch64 - fails:
```
$ cat /usr/local/var/log/sommelier.log
... cut ...
Errors from xkbcomp are not fatal to the X server
Failed to initialize glamor, falling back to sw
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
```
- i686 - fails (as expected):
```
$ tail /usr/local/var/log/sommelier.log
/usr/local/bin/sommelier: line 18: /usr/local/bin/../lib/ld-linux-i686.so.2: No such file or directory
$ ls - /usr/local/lib/ld-linux*
lrwxrwxrwx 1 chronos chronos 10 Oct 17 12:24 /usr/local/lib/ld-linux.so.2 -> ld-2.23.so
```

**Comment by satmandu** [comment]
@uberhacker Isn't that aarch64 failure expected? That's just saying that enabling glamor for acceleration failed, and so it is falling back to using llvmpipe. Has acceleration ever worked on aarch64?

**Comment by satmandu** [comment]
I rebuilt the i686 version, fixing the ld-2.23.so link. I don't expect it to work on i686, but you can test it if you want with: `CREW_TESTING_REPO=https://github.com/uberhacker/chromebrew.git CREW_TESTING_BRANCH=update-sommelier CREW_TESTING=1 crew update ; crew reinstall sommelier` on i686.

**Comment by satmandu** [comment]
I suspect the aarch64 failure is due to a 64 bit kernel and 32 bit mesa drivers...

Having said that, I wonder if we could inject 64-bit mesa drivers and see if that works... isn't the crostini on aarch64 machines 64 bit?

**Comment by uberhacker** [comment]
> @uberhacker Isn't that aarch64 failure expected? That's just saying that enabling glamor for acceleration failed, and so it is falling back to using llvmpipe. Has acceleration ever worked on aarch64?

But the sommelier service didn't start.  That is the important issue.  It has worked with earlier releases.

**Comment by uberhacker** [comment]
> I suspect the aarch64 failure is due to a 64 bit kernel and 32 bit mesa drivers...
> 
> Having said that, I wonder if we could inject 64-bit mesa drivers and see if that works... isn't the crostini on aarch64 machines 64 bit?

Not sure but Linux apps works on this Chromebook so I would assume yes?

**Comment by satmandu** [comment]
> > @uberhacker Isn't that aarch64 failure expected? That's just saying that enabling glamor for acceleration failed, and so it is falling back to using llvmpipe. Has acceleration ever worked on aarch64?
> 
> But the sommelier service didn't start. That is the important issue. It has worked with earlier releases.

Ok that's an issue then... Did you also get this issue in the log indicating Xwayland had segfaulted? (like @ncdm-stldr saw on his machine? - I forget if he had an `aarch64` machine.)
```
(EE)
(EE) Backtrace:
(EE)
(EE) Segmentation fault at address 0x0
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
```

(And this was after the last xwayland update from yesterday?)

**Comment by uberhacker** [comment]
> > > @uberhacker Isn't that aarch64 failure expected? That's just saying that enabling glamor for acceleration failed, and so it is falling back to using llvmpipe. Has acceleration ever worked on aarch64?
> > 
> > 
> > But the sommelier service didn't start. That is the important issue. It has worked with earlier releases.
> 
> Ok that's an issue then... Did you also get this issue in the log indicating Xwayland had segfaulted? (like @ncdm-stldr saw on his machine? - I forget if he had an `aarch64` machine.)
> 
> ```
> (EE)
> (EE) Backtrace:
> (EE)
> (EE) Segmentation fault at address 0x0
> (EE)
> Fatal server error:
> (EE) Caught signal 11 (Segmentation fault). Server aborting
> (EE)
> ```
> 
> (And this was after the last xwayland update from yesterday?)

No, the log message I displayed is all that was in there.

**Comment by satmandu** [comment]
(@uberhacker Please try rebuilding for aarch64 with the older sommelier source git hash but the rest of the current sommelier.rb to see if that works for you?)

**Comment by uberhacker** [comment]
> (@uberhacker Please try rebuilding for aarch64 with the older sommelier source git hash but the rest of the current sommelier.rb to see if that works for you?)

Which hash?  There have been a ton of pushes. :sweat_smile:

**Comment by satmandu** [comment]
> > (@uberhacker Please try rebuilding for aarch64 with the older sommelier source git hash but the rest of the current sommelier.rb to see if that works for you?)
> 
> Which hash? There have been a ton of pushes. 😅

`git_hashtag 'b63df163ab11f07b63d0e7a866f044aa07c7e0b2'`

**Comment by ncdm-stldr** [comment]
@satmandu  Maybe I'll try a `git bisect` later, because it seems to me I did not have these error logs using a previous commit of this branch.
(Yes I have a aarch64 machine by the way. Probably with a 32 bit userland.)

**Comment by satmandu** [comment]
> @satmandu Maybe I'll try a `git bisect` later, because it seems to me I did not have these error logs using a previous commit of this branch. (Yes I have a aarch64 machine by the way. Probably with a 32 bit userland.)

AFAIK the plan was to introduce an aarch64 userland in 2022... but then the Google arm pixel book got canceled and the entire team working on it was let go...

Definitely use the current sommelier.rb in this PR, and start with replacing the `git_hashtag` line with `git_hashtag 'b63df163ab11f07b63d0e7a866f044aa07c7e0b2'` to see if that fixes your issue... if not yes I would definitely try bisecting by going further back...

Can you also see what `uname -a` gives you inside crostini on your aarch64 machine?

**Comment by ncdm-stldr** [comment]
@satmandu 

Here is what I did (provided I made no mistake in the process).

## Step 1
I took `sommelier.rb` from the last commit of this PR (commit 8f90617591ce0dc875d80ff7751d526bd80d2218). Inside sommelier.rb I replaced `git_hashtag 'dbd90c6b002f7d0867cc0b0f1538cc979b688d13'` by `git_hashtag 'b63df163ab11f07b63d0e7a866f044aa07c7e0b2'`. Then I did `crew reinstall sommelier` and `restartsommelier`. It added this in `/usr/local/var/log/sommelier.log`:
```
sommelier -X --x-display=:0 --scale=1 --direct-scale --glamor --force-drm-device=/dev/dri/renderD128 --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=/usr/local/lib/dri --peer-cmd-prefix=/usr/local/lib/ld-linux-armhf.so.3 --enable-xshape --noop-driver --no-exit-with-child /bin/sh -c "touch ~/.Xauthority xauth -f ~/.Xauthority add :0 . bacde6808c213c3e2756ed9ea784d020 source /usr/local/etc/sommelierrc"
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
~/.Xauthority: 1: ~/.Xauthority: Syntax error: Unterminated quoted string
Child exited with status: 2
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
```

## Step 2
Same as Step1 except that I kept `sommelier.rb` without making the modification:
```
sommelier -X --x-display=:0 --scale=1 --direct-scale --glamor --force-drm-device=/dev/dri/renderD128 --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=/usr/local/lib/dri --peer-cmd-prefix=/usr/local/lib/ld-linux-armhf.so.3 --enable-xshape --noop-driver --no-exit-with-child /bin/sh -c "touch ~/.Xauthority xauth -f ~/.Xauthority add :0 . 9f958b25dad4397d8ad6fd12230b9433 source /usr/local/etc/sommelierrc"
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
~/.Xauthority: 1: ~/.Xauthority: Syntax error: Unterminated quoted string
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
Child exited with status: 2
```

## Step 3
I tried the first commit of this PR (2925ef529e0f5f27e2e410b1da96c32d0ca8cab9):
```
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
/bin/sh: 3: source: not found
Child exited with status: 127
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
```

## Step 4
Before this PR:
```
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
(EE) could not connect to wayland server
```

 ## `uname -a` inside crostini
(I do not use chomebrew inside crostini).
```
uname -a
Linux penguin 5.10.153-20434-g98da1eb2cf9d #1 SMP PREEMPT Mon Jan 23 18:46:35 PST 2023 aarch64 GNU/Linux
```

## `uname -a` inside chromeos with crosh terminal
Maybe you don't need it but just in case:
```
uname -a
Linux localhost 5.15.77-14430-g89aabe014a6d #1 SMP PREEMPT Tue Jan 24 19:26:35 PST 2023 aarch64 GNU/Linux
```

----------------

I was wondering what is the connection between google and the chromebrew project? (I mean is chromebrew somewhat supported by google?)

**Comment by satmandu** [comment]
Chromebrew is not supported by Google at all. 

Interesting that crostini IS aarch64, which means that your device does support an aarch64 userland! (Just in crostini...)

Steps 1 and 2 indicate that something between `b63df163ab11f07b63d0e7a866f044aa07c7e0b2` and `dbd90c6b002f7d0867cc0b0f1538cc979b688d13` broke sommelier for `aarch64`. Would you be willing to bisect?

There are 10 commits between those at https://chromium.googlesource.com/chromiumos/platform2.git/+log/HEAD/vm_tools/sommelier

**Comment by satmandu** [comment]
Having said that, it might make sense to try to build an aarch64 sommelier, and point that to the glibc ld-so from inside crostini, to see if that works for Chromebrew on those machines... The kernel is clearly able to run aarch64 executables... can one load an aarch64 binary from within the crosh environment? (I assume that crosvm is an aarch64 binary...)

**Comment by smartguy1196** [comment]
man, I wish I was as proficient with `git` as you guys

**Comment by ncdm-stldr** [comment]
> Steps 1 and 2 indicate that something between `b63df163ab11f07b63d0e7a866f044aa07c7e0b2` and `dbd90c6b002f7d0867cc0b0f1538cc979b688d13` broke sommelier for `aarch64`. Would you be willing to bisect?

I don't really understand how you see this. Logs of step1 and 2 both seem the same. Except for `Child exited with status: 2` which is in a different line in the logs.

**Comment by satmandu** [comment]
> Child exited with status: 2

@ncdm-stldr I'd assumed this meant that either sommlier or Xwayland was crashing. Can you see if you can open `xterm` when this happens?

glamor is only used by Xwayland for acceleration. If Xwayland is failing to run, then glamor isn't an issue.

If you're running gnome-terminal in wayland mode, you won't see an issue with sommelier failing, since then you aren't running under Xwayland.

**Comment by ncdm-stldr** [comment]
@satmandu
Ok interesting.
Xterm does start but is white (except for the bar at the top of the window).
I also tried zutty (also a terminal using the X server), and it looks the same.
When I type it stays white, and no character is printed. But the commands I type blindly work, and I can even copy paste the invisible text in zutty.
It does so with step 1 2 and 3.  (With step 4 none of them start of course).

**Comment by satmandu** [comment]
@uberhacker Do you see the same thing on aarch64? @ncdm-stldr I have no idea why you're getting blank screens with X apps... 😒

Do gnome apps work fine with wayland without using sommelier? 

e.g. `GDK_BACKEND=wayland WAYLAND_DISPLAY=wayland-0 gnome-terminal`

**Comment by ncdm-stldr** [comment]
> Do gnome apps work fine with wayland without using sommelier?
> 
> e.g. `GDK_BACKEND=wayland WAYLAND_DISPLAY=wayland-0 gnome-terminal`

## Gnome-terminal without sommelier
If I don't start sommelier:
```
GDK_BACKEND=wayland WAYLAND_DISPLAY=wayland-0 gnome-terminal
# Failed to parse arguments: Cannot open display:
```
If I start sommelier then it works.

## Alacritty without sommelier
However alacritty (also a terminal) starts and displays itself even without sommelier:
```
alacritty --print-events
Created log file at "/usr/local/tmp/Alacritty-29818.log"
[0.000006146s] [INFO ] [alacritty] Welcome to Alacritty
[0.000260469s] [INFO ] [alacritty] Version 0.11.0
[0.000291302s] [INFO ] [alacritty] Running on Wayland
[0.000465417s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.000902656s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.000951198s] [INFO ] [alacritty] glutin event: Resumed
[0.118459844s] [INFO ] [alacritty] Running on llvmpipe (LLVM 15.0.7, 128 bits)
[0.118578125s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.138350990s] [INFO ] [alacritty] Display scale factor: 2
[0.154395885s] [INFO ] [alacritty] Font size changed to Size(22) with scale factor of 2
[0.162551771s] [INFO ] [alacritty] Cell size: 18 x 41
[0.162633438s] [INFO ] [alacritty] Padding: 0 x 0
[0.162648281s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.162713333s] [INFO ] [alacritty] PTY dimensions: 29 x 88
[0.170848802s] [INFO ] [alacritty] Initialisation complete
[0.170964688s] [INFO ] [alacritty] glutin event: NewEvents(Poll)
[0.170991250s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(38414928)), event: ScaleFactorChanged { scale_factor: 2.0, new_inner_size: PhysicalSize { width: 1600, height: 1200 } } }
[0.171027656s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(38414928)), event: Resized(PhysicalSize { width: 1600, height: 1200 }) }
[0.171042656s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(38414928)), event: Focused(false) }
[0.171053906s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(38414928)), event: Ime(Enabled) }
(...)
```
The screen refresh is a bit glitched, but I suppose this is an alacritty bug.

 ## Other random observations
The xterm and zutty terminals don't react to shortcuts  like "alt + ]" for example. But gnome-terminal and alacritty do.

**Comment by satmandu** [comment]
Do you have a package for alacritty, or have you just done a local compile?

**Comment by ncdm-stldr** [comment]
> Do you have a package for alacritty, or have you just done a local compile?

Yes I did a local compile.

**Comment by satmandu** [comment]
@ncdm-stldr when you have alacritty running, can you do a `preg Xwayland` and see if that shows anything?

also a `glxinfo -B` would be informative. (That's in `mesa_utils`)

**Comment by satmandu** [comment]
If `pgrep Xwayland` shows something, then sommelier didn't shut down completely, and you should do a `stopsommelier  ; pkill Xwayland`...

**Comment by ncdm-stldr** [comment]
@satmandu 
```
chronos@localhost /usr/local/lib/crew/packages $ alacritty &
[1] 3651
chronos@localhost /usr/local/lib/crew/packages $ pgrep Xwayland
chronos@localhost /usr/local/lib/crew/packages $ glxinfo -B
Error: unable to open display :0
chronos@localhost /usr/local/lib/crew/packages $ stopsommelier  ; pkill Xwayland
chronos@localhost /usr/local/lib/crew/packages $
```

**Comment by ncdm-stldr** [comment]
@satmandu Is sommelier normally required for application using wayland?

**Comment by satmandu** [comment]
> @satmandu Is sommelier normally required for application using wayland?

No it is not, but it can act as a wayland proxy.... having said that, the Exo wayland compositor is problematic as it doesn't support newer functionality needed by many newer wayland programs... e.g. `wl_compositor interface version 4` (Exo only advertises version 3).

**Comment by satmandu** [comment]
(For instance try running `foot` from https://github.com/chromebrew/chromebrew/pull/7911 )

**Comment by satmandu** [comment]
@ncdm-stldr Did you build alacritty with both X11 and wayland support?

**Comment by ncdm-stldr** [comment]
> @ncdm-stldr Did you build alacritty with both X11 and wayland support?

Well sorry, I realize that what I said is not correct. I did not install it from source (I confused with another program).
I used the cargo package manager (cargo was installed with `crew install rust` I believe).
Then I used `cargo install alacritty` (like [here](https://github.com/alacritty/alacritty/blob/master/INSTALL.md)). I guess it downloaded the binary.
Next time I will try to build it without support for either the X11 or Wayland to see what happens.

**Comment by satmandu** [comment]
Alacritty defaults to Wayland... As I discovered when I just built it. Should have a package up for it tomorrow...

**Comment by satmandu** [comment]
I find that you can force alacritty to use X11 by doing this: `WAYLAND_DISPLAY= alacritty`

**Comment by satmandu** [comment]
@ncdm-stldr Any more luck figuring out which versions of sommelier work for you?

@uberhacker We should get one of these sommelier updates merged since the current version is more broken, right?

**Comment by uberhacker** [comment]
Should we get some of these new options added to the config or at least document what is possible in a postinstall message?

**Comment by satmandu** [comment]
@uberhacker Which options do you think should be mentioned in a postinstall and/or user-configurable?

**Comment by ncdm-stldr** [comment]
> @ncdm-stldr Any more luck figuring out which versions of sommelier work for you?

No more luck, sadly. But at least sommelier wayland works.

**Comment by uberhacker** [comment]
> WAYLAND_DISPLAY= alacritty

See above.  Also it might be good to explain the difference between `GDK_BACKEND=x11` vs `GDK_BACKEND=wayland` among other environment settings and which config file to edit for changes.

**Comment by satmandu** [comment]
> > WAYLAND_DISPLAY= alacritty
> 
> See above.  Also it might be good to explain the difference between `GDK_BACKEND=x11` vs `GDK_BACKEND=wayland` among other environment settings and which config file to edit for changes.

`WAYLAND_DISPLAY= alacritty` is literally just unsetting `WAYLAND_DISPLAY` though...

**Comment by satmandu** [comment]
`GDK_BACKEND` is only used by gtk3 & gtk4 apps, as I understand it ... Qt apps use a different environment variable, as does Firefox. Enabling Wayland for apps is not by any means uniform...

**Comment by satmandu** [comment]
We also might want to leave the env variable toggles for various wayland/x11 options to a faq on our site, instead of cluttering the package file...

**Comment by uberhacker** [comment]
> We also might want to leave the env variable toggles for various wayland/x11 options to a faq on our site, instead of cluttering the package file...

That would work and we could add a link to the faq/wiki page in the postinstall message.

**Comment by uberhacker** [comment]
Still getting an error on aarch64.  See below:
```
sommelier -X --x-display=:0 --scale=1 --direct-scale --glamor --force-drm-device= --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=/usr/local/lib/dri --peer-cmd-prefix=/usr/local/lib/ld-linux-armhf.so.3 --enable-xshape --noop-driver --no-exit-with-child /bin/sh -c "touch ~/.Xauthority xauth -f ~/.Xauthority add :0 . ee1f8a5c1e0826d51f440080f286384c source /usr/local/etc/sommelierrc"
error: could not open  (No such file or directory)
```
Not detecting the correct render device, apparently.  See below:
```
$ ls -l /dev/dri/
total 0
crw-rw----. 1 root video 226,   0 Feb 14 18:59 card0
crw-rw----. 1 root video 226,   1 Feb 14 18:59 card1
crw-rw----. 1 root video 226,   2 Feb 14 18:59 card2
crw-rw----. 1 root video 226, 128 Feb 14 18:59 renderD128
crw-rw----. 1 root video 226, 129 Feb 14 18:59 renderD129
```
