### PR TITLE
glibc 2.37 patchelf workaround for ChromeOS broken glibc 2.37 & fix upgrades for is_fake pkgs

### LINKED ISSUE #10009: 🐞 Bug libstdc++.so.6 (in Glibc) broken in x86_64 hatch m125 container
```
-- The CXX compiler identification is Clang 18.1.8
-- Detecting CXX compiler ABI info
-- The C compiler identification is Clang 18.1.8
-- The CXX compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Check for working CXX compiler: /usr/local/bin/clang++ - broken
CMake Error at /usr/local/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/usr/local/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/usr/local/tmp/crew/ponyc.20240622074005.dir/build/build_libs/gbenchmark-prefix/src/gbenchmark-build/CMakeFiles/CMakeScratch/TryCompile-3yBLsN'
    
    Run Build Command(s): /usr/local/bin/cmake -E env VERBOSE=1 /usr/local/bin/make -f Makefile cmTC_5212d/fast
    make[4]: Entering directory '/usr/local/tmp/crew/ponyc.20240622074005.dir/build/build_libs/gbenchmark-prefix/src/gbenchmark-build/CMakeFiles/CMakeScratch/TryCompile-3yBLsN'
    /usr/local/bin/make  -f CMakeFiles/cmTC_5212d.dir/build.make CMakeFiles/cmTC_5212d.dir/build
    make[5]: Entering directory '/usr/local/tmp/crew/ponyc.20240622074005.dir/build/build_libs/gbenchmark-prefix/src/gbenchmark-build/CMakeFiles/CMakeScratch/TryCompile-3yBLsN'
    Building CXX object CMakeFiles/cmTC_5212d.dir/testCXXCompiler.cxx.o
    /usr/local/bin/clang++   -fpic  -MD -MT CMakeFiles/cmTC_5212d.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_5212d.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_5212d.dir/testCXXCompiler.cxx.o -c /usr/local/tmp/crew/ponyc.20240622074005.dir/build/build_libs/gbenchmark-prefix/src/gbenchmark-build/CMakeFiles/CMakeScratch/TryCompile-3yBLsN/testCXXCompiler.cxx
    Linking CXX executable cmTC_5212d
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5212d.dir/link.txt --verbose=1
    /usr/local/bin/clang++ -fpic  -flto=auto  CMakeFiles/cmTC_5212d.dir/testCXXCompiler.cxx.o -o cmTC_5212d
    /usr/local/bin/ld: /usr/local/bin/../lib64/LLVMgold.so: error loading plugin: /usr/local/lib64/libstdc++.so.6: undefined symbol: strtof128
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    make[5]: *** [CMakeFiles/cmTC_5212d.dir/build.make:100: cmTC_5212d] Error 1
    make[5]: Leaving directory '/usr/local/tmp/crew/ponyc.20240622074005.dir/build/build_libs/gbenchmark-prefix/src/gbenchmark-build/CMakeFiles/CMakeScratch/TryCompile-3yBLsN'
    make[4]: *** [Makefile:127: cmTC_5212d/fast] Error 2
    make[4]: Leaving directory '/usr/local/tmp/crew/ponyc.20240622074005.dir/build/build_libs/gbenchmark-prefix/src/gbenchmark-build/CMakeFiles/CMakeScratch/TryCompile-3yBLsN'
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:17 (project)
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #10009 #10148

- **_DOES THIS CAUSE STACK SMASHING ERRORS on x86_64 post M-123 devices?_**

- This implements a workaround using `patchelf` to make the system glibc ([which doesn't have float128 functions enabled on x86_64](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/refs/heads/release-R128-15964.B/sys-libs/glibc/files/local/glibc-2.37/0003-Disable-float128-support-for-x86_64-x86.patch)) fall through to _our_ glibc `libc.so.6`, renamed to `libC.so.6` which has float128 functions ( strtof128, strfromf128, and __strtof128_nan ) enabled.

- Works properly:
[x] `x86_64`
[x] `i686` (`i686` doesn't use newer glibc...)
[x] `armv7l` (`armv7l` doesn't have a broken glibc.)

### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=glibc237 crew update && yes | crew upgrade
```

### CODE REVIEW

**Comment by satmandu** [comment]
I need this checked on actual hardware... for some reason I don't get a prompt in the container to upgrade glibc_lib237...

**Comment by satmandu** [comment]
This needs to be checked on actual hardware...

File: packages/glibc_lib237.rb [hunk 1]
```diff
@@ -42,10 +41,42 @@ def self.install
...
+  end
+
+  def self.postinstall
+    if (ARCH == 'x86_64') && (LIBC_VERSION.to_f >= 2.35)
+      FileUtils.cp "/#{ARCH_LIB}/libc.so.6", File.join(CREW_LIB_PREFIX, 'libc.so.6.system') and FileUtils.mv File.join(CREW_LIB_PREFIX, 'libc.so.6.system'), File.join(CREW_LIB_PREFIX, 'libc.so.6') unless Kernel.system "patchelf --print-needed #{File.join(CREW_LIB_PREFIX, 'libc.so.6')} | grep -q libC.so.6"
+      puts "patchelf is needed. Please run: 'crew install patchelf ; crew postinstall #{name}'".lightred unless File.file?(File.join(CREW_PREFIX, 'bin/patchelf'))
+      # Link the system libc.so.6 to also require our renamed libC.so.6
+      # which provides the float128 functions strtof128, strfromf128,
+      # and __strtof128_nan.
+      @libc_patch_libraries = %w[libc.so.6 libm.so.6 libstdc++.so.6]
```
Comment (Zopolis4) [inline packages/glibc_lib237.rb:66]: This doesn't need to be an instance variable.

File: lib/fixup.rb [hunk 2]
```diff
@@ -189,3 +189,25 @@ def self.remove; end
...
 # Remove pagerenv tmp file in CREW_PACKAGES_PATH if it exists
 FileUtils.rm "#{CREW_PACKAGES_PATH}/pagerenv" if File.file?("#{CREW_PACKAGES_PATH}/pagerenv")
+
+# Handle broken system glibc affecting gcc_lib on newer x86_64 ChromeOS milestones.
+if (ARCH == 'x86_64') && (LIBC_VERSION.to_f >= 2.36)
+  abort("patchelf is needed. Please run: 'crew install patchelf && crew update'") unless File.file?(File.join(CREW_PREFIX, 'bin/patchelf'))
+  # Link the system libc.so.6 to also require our renamed libC.so.6
+  # which provides the float128 functions strtof128, strfromf128,
+  # and __strtof128_nan.
+  @libc_patch_libraries = %w[libstdc++.so.6]
```
Comment (Zopolis4) [inline lib/fixup.rb:199]: This also does not need to be an instance variable, and it probably doesn't need to be an array.

Comment (satmandu) [reply lib/fixup.rb:199]: The array is there in case we have to add more libraries.

File: packages/glibc_lib237.rb [hunk 3]
```diff
@@ -42,10 +41,42 @@ def self.install
       FileUtils.install @filename_target, @destpath
     end
     # Symlinks to system libraries.
-    %w[libanl.so.1 libc_malloc_debug.so.0 libc.so.6 libdl.so.2 libm.so.6
-       libmvec.so.1 libnss_dns.so.2 libnss_files.so.2 libpthread.so.0
-       libresolv.so.2 librt.so.1 libthread_db.so.1 libutil.so.1].each do |lib|
-      FileUtils.ln_sf "/#{ARCH_LIB}/#{lib}", "#{CREW_DEST_LIB_PREFIX}/#{lib}"
+    @glibc_libs = %w[libanl.so.1 libc_malloc_debug.so.0 libc.so.6 libdl.so.2 libm.so.6
```
Comment (Zopolis4) [inline packages/glibc_lib237.rb:44]: This also doesn't need to be an instance variable.

File: packages/glibc_lib237.rb [hunk 4]
```diff
@@ -42,10 +41,42 @@ def self.install
...
+      if ARCH == 'x86_64'
+        puts "skipping symlink of system/#{ARCH_LIB}/#{lib} into #{CREW_DEST_LIB_PREFIX}/#{lib}...".orange
+      else
+        FileUtils.ln_sf "/#{ARCH_LIB}/#{lib}", "#{CREW_DEST_LIB_PREFIX}/#{lib}"
+      end
+    end
+  end
+
+  def self.postinstall
+    if (ARCH == 'x86_64') && (LIBC_VERSION.to_f >= 2.35)
```
Comment (Zopolis4) [inline packages/glibc_lib237.rb:60]:
```suggestion
    if (ARCH == 'x86_64') && (LIBC_VERSION >= '2.35')
```

from my testing in irb, no need to convert to a float here.

File: packages/glibc_lib237.rb [hunk 5]
```diff
@@ -42,10 +41,42 @@ def self.install
...
+      FileUtils.cp "/#{ARCH_LIB}/libc.so.6", File.join(CREW_LIB_PREFIX, 'libc.so.6.system') and FileUtils.mv File.join(CREW_LIB_PREFIX, 'libc.so.6.system'), File.join(CREW_LIB_PREFIX, 'libc.so.6') unless Kernel.system "patchelf --print-needed #{File.join(CREW_LIB_PREFIX, 'libc.so.6')} | grep -q libC.so.6"
+      puts "patchelf is needed. Please run: 'crew install patchelf ; crew postinstall #{name}'".lightred unless File.file?(File.join(CREW_PREFIX, 'bin/patchelf'))
+      # Link the system libc.so.6 to also require our renamed libC.so.6
+      # which provides the float128 functions strtof128, strfromf128,
+      # and __strtof128_nan.
+      libc_patch_libraries = %w[libc.so.6 libm.so.6 libstdc++.so.6]
+      libc_patch_libraries.delete_if { |lib| !File.file?(File.join(CREW_LIB_PREFIX, lib)) }
```
Comment (Zopolis4) [inline packages/glibc_lib237.rb:67]: I think `.keep_if` would work here and might be a little clearer than an inverted delete_if, but i'm not too fussed about it.

File: packages/glibc_lib237.rb (hunk 4 above)
Comment (satmandu) [reply packages/glibc_lib237.rb]: Looks like the conversion is necessary:

```
Performing post-install for glibc_lib237...
/usr/local/lib/crew/packages/glibc_lib237.rb:60:in `>=': comparison of String with 2.35 failed (ArgumentError)
```

**Comment by satmandu** [comment]
@uberhacker Please do not merge until tested on actual hardware...

**Review by uberhacker — APPROVED** [review]
