### PR TITLE
Fix error with autotools builds

### LINKED ISSUE #9997: 🐞 Bug Issue with autotools buildsystem
```
Additional configure_options being used: <no pre_configure_options> --localstatedir=/usr/local/tmp
Command "bash -c grep -q /usr/bin/file configure" failed, retrying with "-j1"...
There was a build error.
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #9997.

### CODE REVIEW

File: lib/buildsystems/autotools.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def self.build
       end
       abort 'configure script not found!'.lightred unless File.file?('configure')
       FileUtils.chmod('+x', 'configure')
-      if system('grep -q /usr/bin/file configure')
+      if File.executable? "#{CREW_PREFIX}/bin/file"
         puts 'Using filefix.'.orange
```
Comment (satmandu) [inline lib/buildsystems/autotools.rb:23]: Shouldn't we only report we are running filefix if `/usr/bin/file` is actually in the configure script?

Sure checking to see if a local copy of `file` exists first too is a good idea, but that check can come afterwards only if we actually need to run filefix...

Comment (uberhacker) [reply lib/buildsystems/autotools.rb:23]: I think it should be fine?  It aborts if configure is not found 2 lines above that.

File: lib/buildsystems/autotools.rb [hunk 2]
```diff
@@ -19,7 +19,7 @@ def self.build
       end
       abort 'configure script not found!'.lightred unless File.file?('configure')
       FileUtils.chmod('+x', 'configure')
-      if system('grep -q /usr/bin/file configure')
```
Comment (Zopolis4) [inline lib/buildsystems/autotools.rb:22]: The problem here is that our custom system command defined in `lib/package.rb` will retry on failure, where here we actually don't want it do do that. @supechicken, any ideas on how to access the ruby `system` here? Maybe `Kernel.system()`?

I've got plans to refactor that system code out into `commands/build.rb` to stop leakages like this, but that won't happen until most other commands are refactored, and isn't a timely solution to this problem.

Comment (uberhacker) [reply lib/buildsystems/autotools.rb:22]: This is not simple to Rubyize.  If someone has a better solution, I'm all ears.
```
     search = false
      Dir['**/*'].grep(/config$/).each do |filename|
        File.open(filename) do |file|
          file.each_line do |line|
            if line =~ /\/usr\/bin\/file/  
              search = true
              break
            end
          end
        end
      end
      if search
        puts 'Using filefix.'.orange
        system 'filefix'
      end
```
It does no harm to run filefix on every config file even if `/usr/bin/file` doesn't exist.  The filefix program itself can do the checking and fixing in one go.

Comment (Zopolis4) [reply lib/buildsystems/autotools.rb:22]: No, I'm simply saying is there a way to run the default `system()` command rather than the one from `lib/package.rb`

Comment (Zopolis4) [reply lib/buildsystems/autotools.rb:22]: What package did you encounter the bug on? I'd like to test `Kernel.system()`.

Comment (uberhacker) [reply lib/buildsystems/autotools.rb:22]: I was trying to update a2ps.rb.

Comment (Zopolis4) [reply lib/buildsystems/autotools.rb:22]: For what its worth, I'm working on that as well: https://github.com/Zopolis4/chromebrew/tree/0a. Might be best to avoid doubling up. I should PR my branches sooner :sweat_smile:.

Comment (Zopolis4) [reply lib/buildsystems/autotools.rb:22]: Tested, using `Kernel.system()` works.

File: lib/buildsystems/autotools.rb [hunk 3]
```diff
@@ -19,7 +19,7 @@ def self.build
...
+      if File.executable? "#{CREW_PREFIX}/bin/file"
```
Comment (Zopolis4) [inline lib/buildsystems/autotools.rb:22]: `if Kernel.system('grep -q /usr/bin/file configure')`?

**Review by Zopolis4 — CHANGES_REQUESTED** [review]

File: lib/buildsystems/autotools.rb (hunk 2 above)
Comment (satmandu) [reply lib/buildsystems/autotools.rb:22]: > Tested, using `Kernel.system()` works.

Yeah I noticed that too. I mentioned it to @uberhacker and as I understand it he's going to update the PR accordingly.

Comment (satmandu) [reply lib/buildsystems/autotools.rb:22]: We should probably figure out though why `system()` is broken though. 😅

Comment (Zopolis4) [reply lib/buildsystems/autotools.rb:22]: As I said, its because we define a custom `system()` in `lib/package.rb` that restarts with `make -j1` on errors instead of failing.

Comment (satmandu) [reply lib/buildsystems/autotools.rb:22]: Yes. We should fix the custom `system()`...

That's the root cause of this issue.

Comment (Zopolis4) [reply lib/buildsystems/autotools.rb:22]: The custom `system()` is working as intended, that's what its supposed to do. Although, it might be nice to find a way to isolate that to package files only, rather than having to use `Kernel.system()` to override it.

**Review by Zopolis4 — APPROVED** [review]
