### PR TITLE
install.sh: Some improvements

### LINKED ISSUE #9923: 🐞 Bug - Installation issue - OPENSSL_3.2.0 not found
I tried to install chromebrew and the process stopped at this point:
OPENSSL_3.2.0 not found
Screenshot 2024-06-07 19 34 53

I hope there's a way to fix it or any workaround is appreciated. Thank you

### LINKED ISSUE #9934: 🐞 Bug unable to install on stable channel
**Describe the bug**
When installing Chromebrew on latest brand-new ChromeOS system on stable channel it refuses to install because "The beta, dev and canary channel are unsupported by Chromebrew"

**To Reproduce**
Steps to reproduce the behavior: Install latest stable ChromeOS with brunch, then try installing Chromebrew

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): VT-2

2. I executed the command(s) below:
      ```shell
     curl -L git.io/vddgY > install.sh
     cp install.sh /usr/local
     cd /usr/local
     bash install.sh
      ```

      Output:

      ```
      The beta, dev and canary channel are unsupported by Chromebrew.
      Run 'CREW_FORCE_INSTALL=1 exec bash --init-file <(curl -Ls git.io/vddgY)' to perform install anyway 
      ```
**Expected behavior**
Chromebrew installation

**Screenshots**
image
image

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
chronos@brunch ~ $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=33
CHROMEOS_ARC_VERSION=11865392
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={0BE68F68-A2F2-46B7-A7B4-B51B63F64FBA}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={0BE68F68-A2F2-46B7-A7B4-B51B63F64FBA}
CHROMEOS_RELEASE_BOARD=zork-signed-mp-v9keys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=zork-release/R125-15853.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=15853
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=125
CHROMEOS_RELEASE_DESCRIPTION=15853.53.0 (Official Build) stable-channel zork 
CHROMEOS_RELEASE_KEYSET=mp-v9
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=15853.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=15853.53.0
***

**Additional context**
I've got the latest **stable** releases of both ChromeOS and Brunch, ChromeOS is on stable-channel so I have no idea about what is causing this

### PR DESCRIPTION
**Pull request by supechicken**
Fixes #9934, fixes #9923

### Changes
- Bashify some commands (like changing `basename $var` to `${var##*/}`)
- Stop system binaries from accessing chromebrew libraries, preventing issues like #9923 happen again
- Change version checking regex to a `grep` command, which should fix #9934
- Hardcoded developer mode password file path as it is unlikely to change in the future
- Removed `LD_LIBRARY_PATH` env variable setting logic, as it should be handled in `crew-profile-base` instead

Tested on `aarch64`

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -25,26 +25,27 @@ fi
 # Reject crostini.
 if [[ -d /opt/google/cros-containers && "${CREW_FORCE_INSTALL}" != '1' ]]; then
   echo_error "Crostini containers are not supported by Chromebrew :/"
-  echo_info "Run 'CREW_FORCE_INSTALL=1 exec bash --init-file <(curl -Ls git.io/vddgY)' to perform install anyway"
+  echo_info "Run 'CREW_FORCE_INSTALL=1 bash <(curl -L git.io/vddgY) && . ~/.bashrc' to perform install anyway"
```
Comment (uberhacker) [inline install.sh:28]: Simplify further with?
```
... curl -Ls git.io/vddgY | bash ...
```

File: install.sh [hunk 2]
```diff
@@ -25,26 +25,27 @@ fi
...
   exit 1
 fi
 
 # Reject non-stable Chrome OS channels.
 if [ -f /etc/lsb-release ]; then
-  if [[ ! "$(< /etc/lsb-release)" =~ CHROMEOS_RELEASE_TRACK=stable-channel$'\n' && "${CREW_FORCE_INSTALL}" != '1' ]]; then
+  export "$(grep CHROMEOS_RELEASE_CHROME_MILESTONE /etc/lsb-release)"
+
+  if ! (grep -q 'CHROMEOS_RELEASE_TRACK=stable-channel' /etc/lsb-release || [[ "${CREW_FORCE_INSTALL}" == '1' ]]); then
```
Comment (Zopolis4) [inline install.sh:36]: Is there a way to avoid grepping `/etc/lsb-release` twice?

File: install.sh (hunk 1 above)
Comment (supechicken) [reply install.sh:28]: Using pipes will break things like `select` and `read`, as stdin will be redirected to `curl` and no longer connected to the terminal

https://github.com/chromebrew/chromebrew/blob/f78af8f68315bfd6ae2f3017826064e82272f10d/install.sh#L57-L59

Comment (uberhacker) [reply install.sh:28]: Gotcha, good to know.

File: install.sh (hunk 2 above)
Comment (supechicken) [reply install.sh:36]: We can use `mapfile` to parse the whole file first, but I am not familiar with it 😅

**Review by uberhacker — APPROVED** [review]

**Comment by satmandu** [comment]
@supechicken This had to be reverted because it broke all of the container image builds.

**Comment by supechicken** [comment]
> @supechicken This had to be reverted because it broke all of the container image builds.

Hmm it works on real machines... What is the error message?

**Comment by satmandu** [comment]
The git clone never works properly...

**Comment by satmandu** [comment]
If you have the chromeos_docker script, you can put your install.sh in for instance the x86_64 folder as install.sh.test and try the build to generate a container image...

**Comment by uberhacker** [comment]
On the next PR, can we simply fix so we don't need `CREW_FORCE_INSTALL=1` without anything else?  Incremental changes please. :grin:
