### PR TITLE
Have compatibility also notice when min_glibc is too high for a package.

### LINKED ISSUE #10284: 🐞 installs and builds of packages with dependencies with higher min_glibc than current system do not immediately fail
- system is on glibc 2.27
- Package A (e.g., `webkitgtk_6`) has a build dependency on Package B (e.g., `gstreamer`), which has `min_glibc` of `2.37`
- crew allows trying to build package A.
- this should actually fail immediately.
- instead the build continues for 18 hours before eventually failing.

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #10284

- Also edit README to mention `crew list essential` option.
- `crew list compatible | grep gstreamer` will be blank on the older containers...

##
Builds:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`
##
Tested & Working properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 
##
- [x] This PR has no manifest .filelist changes. _(Package changes have neither added nor removed files.)_
##
### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=compatible crew update \
&& yes | crew upgrade
```

### CODE REVIEW

File: lib/package_utils.rb [hunk 1]
```diff
@@ -25,7 +25,7 @@ def self.installed?(pkg_name)
   end
 
   def self.compatible?(pkg)
-    return pkg.compatibility.casecmp?('all') || pkg.compatibility.include?(ARCH)
+    return (pkg.compatibility.casecmp?('all') || pkg.compatibility.include?(ARCH)) && (pkg.min_glibc.nil? ? true : (pkg.min_glibc <= LIBC_VERSION))
```
Comment (uberhacker) [inline lib/package_utils.rb:28]: `(pkg.min_glibc.nil? || (pkg.min_glibc <= LIBC_VERSION))`?

File: README.md [hunk 2]
```diff
@@ -87,7 +87,7 @@ Where available commands are:
 | files        | display installed files of package(s) |
 | help         | get information about command usage |
 | install      | install package(s) along with dependencies after prompting for confirmation |
-| list         | available, installed, compatible or incompatible packages |
+| list         | available, compatible, incompatible, essential, installed packages |
```
Comment (uberhacker) [inline README.md:90]: List alphabetically?

**Comment by uberhacker** [comment]
> Fixes #10284
> 
> * Also edit README to mention `crew list essential` option.
> * `crew list compatibility | grep gstreamer` will be blank on the older containers...
> 
> Builds:
> 
> * [x]  `x86_64`
> * [x]  `i686`
> * [x]  `armv7l`
> 
> Tested & Working properly:
> 
> * [x]  `x86_64`
> * [x]  `i686`
> * [x]  `armv7l`
> 
> * [x]  This PR has no manifest .filelist changes. _(Package changes have neither added nor removed files.)_
> 
> ### Run the following to get this pull request's changes locally for testing.
> ```shell
> CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=compatible crew update \
> && yes | crew upgrade
> ```

`crew list compatible | grep gstreamer`?

**Comment by satmandu** [comment]
> > Fixes #10284
> > 
> > * Also edit README to mention `crew list essential` option.
> > * `crew list compatibility | grep gstreamer` will be blank on the older containers...
> > 
> > Builds:
> > 
> > * [x]  `x86_64`
> > * [x]  `i686`
> > * [x]  `armv7l`
> > 
> > Tested & Working properly:
> > 
> > * [x]  `x86_64`
> > * [x]  `i686`
> > * [x]  `armv7l`
> > 
> > * [x]  This PR has no manifest .filelist changes. _(Package changes have neither added nor removed files.)_
> > 
> > ### Run the following to get this pull request's changes locally for testing.
> > ```shell
> > CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=compatible crew update \
> > && yes | crew upgrade
> > ```
> 
> `crew list compatible | grep gstreamer`?

Yes, that!

File: README.md (hunk 2 above)
Comment (satmandu) [reply README.md:90]: I put those together intentionally so that `compatible` and `incompatible` were logically next to each other.

Comment (satmandu) [reply README.md:90]: How do you feel about that?

Comment (uberhacker) [reply README.md:90]: Well, you could put available and installed together logically too.  I guess it doesn't matter.

**Review by uberhacker — APPROVED** [review]
