### PR TITLE
Mpv -> 0.34.1 and fix deps

### LINKED ISSUE #7324: mpv cannot run
## Description
 running mpv from terminal  outouts error. mpv: error while loading shared libraries: libcdio.so.18: cannot open shared object file: No such file or directory

also tried to do  a crew-launcher add mpv and it outputs:
/usr/local/bin/crew-launcher:84:in `CreateProfile': undefined method `sub' for nil:NilClass (NoMethodError)

    exec: desktop['Desktop Entry']['Exec'].sub(/%[A-Za-z]/, ''),
                                          ^^^^
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'

If you executed a specific command:
```shell
# your command here
```
mpv
Output:
```
# output of your command here
```
mpv: error while loading shared libraries: libcdio.so.18: cannot open shared object file: No such file or directory

## Versions and system information

***
***

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #7324

Works properly:
- [x] `x86_64`
- [x] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=mpv CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/mpv.rb [hunk 1]
```diff
@@ -3,24 +3,22 @@
...
   git_hashtag "v#{@_ver}"
 
   binary_url({
-    i686: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.0_i686/mpv-0.34.0-chromeos-i686.tpxz',
-    aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.0_armv7l/mpv-0.34.0-chromeos-armv7l.tpxz',
-     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.0_armv7l/mpv-0.34.0-chromeos-armv7l.tpxz',
-     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.0_x86_64/mpv-0.34.0-chromeos-x86_64.tpxz'
+ aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.1_armv7l/mpv-0.34.1-chromeos-armv7l.tar.zst',
+  armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.1_armv7l/mpv-0.34.1-chromeos-armv7l.tar.zst',
+  x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/mpv/0.34.1_x86_64/mpv-0.34.1-chromeos-x86_64.tar.zst'
```
Comment (uberhacker) [inline packages/mpv.rb:16]: Indent 3 more spaces?

File: packages/mpv.rb [hunk 2]
```diff
@@ -3,24 +3,22 @@
...
   })
   binary_sha256({
-    i686: 'f74ba4cade2a5bbf454d4541f868022e135fc83771aadb74e73744374c73f1f6',
-    aarch64: '02e091134eedd1a0d468ce9a1032048e1e39d4310df919d41ce15a2ec5995c97',
-     armv7l: '02e091134eedd1a0d468ce9a1032048e1e39d4310df919d41ce15a2ec5995c97',
-     x86_64: '5cfe927d93d12fa456828b62afebff35d182b7105052f6186aef820a40436ebc'
+ aarch64: '60207de3ae34a2e50eb2ffe7202f9ae55ae3edcb156fe9119ad654c67bc7b381',
+  armv7l: '60207de3ae34a2e50eb2ffe7202f9ae55ae3edcb156fe9119ad654c67bc7b381',
+  x86_64: 'f82aed1ae1ed85e1650776bfb738f4948d4c6d8ae38d7d1495d837c5f82675b0'
```
Comment (uberhacker) [inline packages/mpv.rb:21]: Indent 3 more spaces?

**Review by uberhacker — CHANGES_REQUESTED** [review]

File: packages/mpv.rb (hunk 2 above)
Comment (satmandu) [reply packages/mpv.rb]: reindented...

**Review by uberhacker — APPROVED** [review]
