### PR TITLE
Fix fake package removal bug

### LINKED ISSUE #9765: 🐞 Bug Unable to remove fake packages
```
gcc: The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.
Performing pre-flight checks...
Removing since upgrade or reinstall...
/usr/local/lib/crew/commands/remove.rb:28:in `foreach': No such file or directory @ rb_sysopen - /usr/local/etc/crew/meta/gcc.filelist (Errno::ENOENT)
        from /usr/local/lib/crew/commands/remove.rb:28:in `block in remove'
        from /usr/local/lib/crew/commands/remove.rb:26:in `chdir'
        from /usr/local/lib/crew/commands/remove.rb:26:in `remove'
        from /usr/local/bin/crew:1294:in `install'
        from /usr/local/bin/crew:1123:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:436:in `block in upgrade'
        from /usr/local/bin/crew:428:in `each'
        from /usr/local/bin/crew:428:in `upgrade'
        from /usr/local/bin/crew:1886:in `upgrade_command'
        from /usr/local/bin/crew:1916:in `<main>'
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #9765.

### CODE REVIEW

**Review by satmandu — APPROVED** [review]

File: commands/remove.rb [hunk 1]
```diff
@@ -23,28 +23,30 @@ def self.remove(pkg, verbose)
...
-    Dir.chdir CREW_CONFIG_PATH do
-      # Remove all files installed by the package.
-      File.foreach(File.join(CREW_META_PATH, "#{pkg.name}.filelist"), chomp: true) do |line|
-        next unless line.start_with?(CREW_PREFIX)
-        if system("grep --exclude #{pkg.name}.filelist -Fxq '#{line}' ./meta/*.filelist")
-          puts "#{line} is in another package. It will not be removed during the removal of #{pkg.name}.".orange
-        else
-          puts "Removing file #{line}".yellow if verbose
-          FileUtils.remove_file line, exception: false
+    unless pkg.is_fake
```
Comment (Zopolis4) [inline commands/remove.rb:26]: This should be `pkg.is_fake?`-- `pkg.is_fake` always returns true so installs are broken right now.

Comment (Zopolis4) [reply commands/remove.rb:26]: See #9770.
