### PR TITLE
Flatpak update and necessary rebuilds/updates + pip updates.

### LINKED ISSUE #10726: 🐞 Bug - Cannot run flatpak because of missing `libassuan.so.0`
**Describe the bug**
Cannot install flatpak because of missing shared library(`libassuan.so.0`).

**To Reproduce**

1. Please indicate where the command(s) were executed.
bash launched from crosh.

2. I executed the command(s) below:
      ```shell
      crew install flatpak
      flatpak
      ```

      Output:

      ```
      /usr/local/libexec/flatpak/flatpak: error while loading shared libraries: libassuan.so.0: cannot open shared object file: No such file or directory
      ```
**Expected behavior**
flatpak helps show up.

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #10726

##
Builds:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`
##
### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=flatpak crew update \
&& yes | crew upgrade
```

### CODE REVIEW

File: packages/gpgme.rb [hunk 1]
```diff
@@ -3,23 +3,49 @@
...
+
+        pid_t
+        gettid(void)
+        {
+
+            return syscall(SYS_gettid);
+        }
+        #endif
+      GETTID_WRAPPER_EOF
+      File.write('gettid_wrapper', gettid_wrapper)
```
Comment (uberhacker) [inline packages/gpgme.rb:46]: You can combine lines 28 and this one with the following:
```
File.write 'gettid_wrapper', <<~GETTID_WRAPPER_EOF

File: packages/libgpg_error.rb [hunk 2]
```diff
@@ -3,18 +3,20 @@
...
-  version '1.50'
+  version '1.51'
   license 'GPL-2 and LGPL-2.1'
   compatibility 'all'
-  source_url 'https://dev.gnupg.org/source/libgpg-error.git'
-  git_hashtag "libgpg-error-#{version}"
+  source_url "https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-#{version}.tar.bz2"
+  source_sha256 'be0f1b2db6b93eed55369cdf79f19f72750c8c7c39fc20b577e724545427e6b2'
+  # source_url 'https://dev.gnupg.org/source/libgpg-error.git'
+  # git_hashtag "libgpg-error-#{version}"
```
Comment (uberhacker) [inline packages/libgpg_error.rb:12]: Why not keep the source url and use the git hash for git_hashtag instead?

File: packages/libostree.rb [hunk 3]
```diff
@@ -1,44 +1,64 @@
...
       --disable-gtk-doc \
-      --disable-man" # gtk-doc and man failed to build, causes make to fail
-    system 'make'
-  end
+      --disable-man' # gtk-doc and man failed to build, causes make to fail
 
-  def self.install
-    system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
+  def self.prebuild
+    ConvenienceFunctions.libtoolize('libxml2')
```
Comment (uberhacker) [inline packages/libostree.rb:62]: What exactly does this accomplish?

File: packages/npth.rb [hunk 4]
```diff
@@ -1,32 +1,21 @@
...
-  end
-
-  def self.install
-    system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
-  end
-
-  def self.check
-    system 'make', 'check'
-  end
+  depends_on 'glibc' # R
```
Comment (uberhacker) [inline packages/npth.rb:20]: Add `run_tests`?

File: packages/gnupg.rb [hunk 5]
```diff
@@ -39,4 +39,9 @@ class Gnupg < Autotools
     --with-readline'
 
   run_tests
+
+  def self.patch
+    downloader 'https://files.gnupg.net/file/data/zy2tsxkydxq4okdhxj4p/PHID-FILE-cnig3h7b4hnrmr5efbh2/file', '7beaf4c72dc91a885fb088f7c1ef043ab49f230666727bcf2609954d722aba36', 'unistd.patch'
+    system 'patch -Np1 -i unistd.patch'
```
Comment (uberhacker) [inline packages/gnupg.rb:45]: Does `system "git apply unistd.patch"` work?

File: packages/libgpg_error.rb (hunk 2 above)
Comment (satmandu) [reply packages/libgpg_error.rb:12]: As of several hours ago the tag hadn't been pushed yet, though a release had been cut...

File: packages/libostree.rb (hunk 3 above)
Comment (satmandu) [reply packages/libostree.rb:62]: This generates a `libxml2.la` file.

File: packages/npth.rb (hunk 4 above)
Comment (satmandu) [reply packages/npth.rb:20]: Done.

File: packages/libgpg_error.rb (hunk 2 above)
Comment (satmandu) [reply packages/libgpg_error.rb:12]: (They still haven't tagged it...)

File: packages/gnupg.rb (hunk 5 above)
Comment (uberhacker) [reply packages/gnupg.rb:45]: I was just thinking this might be an easier way to do it.  Several other packages are using this method.

File: packages/libgpg_error.rb (hunk 2 above)
Comment (satmandu) [reply packages/libgpg_error.rb:12]: (Also, the weird git server they use doesn't allow us to specify a git hash to specify...)

File: packages/gpgme.rb (hunk 1 above)
Comment (satmandu) [reply packages/gpgme.rb]: Done.

File: packages/libostree.rb (hunk 3 above)
Comment (uberhacker) [reply packages/libostree.rb:62]: Gotcha.

File: manifest/armv7l/b/bubblewrap.filelist [hunk 6]
```diff
@@ -1,5 +1,4 @@
 /usr/local/bin/bwrap
 /usr/local/bin/bwrap.elf
 /usr/local/share/bash-completion/completions/bwrap
-/usr/local/share/man/man1/bwrap.1.zst
```
Comment (uberhacker) [inline manifest/armv7l/b/bubblewrap.filelist:4]: Removing manpages always makes me sad.

File: packages/gnupg.rb (hunk 5 above)
Comment (satmandu) [reply packages/gnupg.rb:45]:
```bash
grep -l "patch -Np1 -i" * | wc -l
55
grep -l "git apply" * | wc -l
14
```

I don't know if the `git apply` command is more prone to issues than using `patch -Np1 -i`.  I haven't done the research on that...

File: manifest/armv7l/b/bubblewrap.filelist (hunk 6 above)
Comment (satmandu) [reply manifest/armv7l/b/bubblewrap.filelist:4]: Agreed. But if there's a build issue with XML file weirdness, which there was here...

Comment (uberhacker) [reply manifest/armv7l/b/bubblewrap.filelist:4]: Kinda makes me wonder if it's worth changing the build method.

Comment (satmandu) [reply manifest/armv7l/b/bubblewrap.filelist:4]: > Kinda makes me wonder if it's worth changing the build method.

For bubblewrap? I doubt it. There is extensive documentation online. Most people are going to Google first...

Comment (uberhacker) [reply manifest/armv7l/b/bubblewrap.filelist:4]: Well, the old method did build the manpage or does it not with this new release?

Comment (satmandu) [reply manifest/armv7l/b/bubblewrap.filelist:4]: Man is set to auto automatically with this release. So if there's an issue in build setup, it won't bother building it.

Comment (satmandu) [reply manifest/armv7l/b/bubblewrap.filelist:4]: We could manually turn it on...

Comment (satmandu) [reply manifest/armv7l/b/bubblewrap.filelist:4]: Ah! I broke `docbook_xsl` in August.... Fixing it...

Comment (satmandu) [reply manifest/armv7l/b/bubblewrap.filelist]: Fixed.

File: packages/libgpg_error.rb (hunk 2 above)
Comment (satmandu) [reply packages/libgpg_error.rb:12]: Still no 1.51 tag: https://dev.gnupg.org/source/libgpg-error/tags/master/

**Review by uberhacker — APPROVED** [review]
