### PR TITLE
icu4c => 74.2

### LINKED ISSUE #9472: Inkscape dependencey not installed properley
**Describe the bug**
inkscape dependencey not installed

**To Reproduce**

1. I executed this command:

      ```shell
      inkscape
      ```

      Output:

      ```
      inkscape: error while loading shared libraries: libboost_filesystem.so.1.83.0: cannot open shared object file: No such file or directory

      ```

**Expected behavior**
I expected it to open

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.44.8`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 6c1545571 `Signal_desktop 6.48.1 => 7.1.1 (#9449) (4 days ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R122-15753.38.0`
- OS channel: `stable-channel`

</details>

***

**Additional context**

What I think needs to be done:

      - Make chromebrew properley install libboost

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #9472 
- Updates `icu4c` to 74.2
- Updates `gedit` and dependencies.
- Re: packages that depend upon `icu4c`...
  -  first removed the container check from the `icu4c` postinstall, then  ran `for i in $(grep icu4c * | sed 's/.rb://' | awk '{print $1}') ; do yes | crew install $i &> /output/icu4c/$i.log ; crew postinstall icu4c &> /output/icu4c/$i.log ; crew remove $i ; done` and checked the resultant logs... which were all empty of errors.
  - `gettext` does not need to be updated.
  - updated: `libxml2`, `postgres`
  - rebuilt `tcl` for i686. (It was missing.)
  - Setup buildsystems postinstalls for common gnome code.

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=gedit crew update ; yes | crew upgrade
```

### CODE REVIEW

File: lib/const.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 # lib/const.rb
 # Defines common constants used in different parts of crew
 
-CREW_VERSION = '1.45.2'
+CREW_VERSION = '1.45.3'
```
Comment (Zopolis4) [inline lib/const.rb:4]: Do we need to bump `CREW_VERSION` for only an addition to the rename list in `lib/fixup.rb`?

Comment (uberhacker) [reply lib/const.rb:4]: I think it makes sense to bump the version for ANY changes, actually.  This makes it possible to go back and find where changes were made.

Comment (uberhacker) [reply lib/const.rb:4]: The exception would be packages updates, of course.

**Review by uberhacker — APPROVED** [review]

File: lib/const.rb (hunk 1 above)
Comment (satmandu) [reply lib/const.rb:4]: I figured it was safer to do so?

File: packages/gedit.rb [hunk 2]
```diff
@@ -1,64 +1,47 @@
...
-    system 'meson configure --no-pager builddir'
-    system 'ninja -C builddir'
-  end
+  meson_options '-Drequire_all_tests=false \
+    -Dgtk_doc=false \
+    -Duser_documentation=true'
 
-  def self.install
-    system "DESTDIR=#{CREW_DEST_DIR} ninja -C builddir install"
+  def self.postinstall
```
Comment (Zopolis4) [inline packages/gedit.rb:45]: The package [already does this](https://gitlab.gnome.org/GNOME/gedit/-/blob/da63f4c642c8ffabb0773f1ef2c2a0edadfdc3e9/meson.build#L165)

Comment (satmandu) [reply packages/gedit.rb:45]: In theory. It didn't work in practice until I ran that. Running it again to make sure that happens won't hurt anything.

Comment (satmandu) [reply packages/gedit.rb:45]: Ah this is why: The post_install scripts are skipped if a `DESTDIR` is specified in the install step. See https://github.com/mesonbuild/meson/issues/8268#issuecomment-770017342

File: lib/buildsystems/autotools.rb [hunk 3]
```diff
@@ -38,4 +38,18 @@ def self.check
...
+    if @gnome
+      puts 'Running Gnome post_installs...'.orange
+      system "glib-compile-schemas #{CREW_PREFIX}/share/glib-2.0/schemas" if File.file?("#{CREW_PREFIX}/bin/glib-compile-schemas")
+      system "gio-querymodules #{CREW_LIB_PREFIX}/gio/modules" if File.file?("#{CREW_PREFIX}/bin/gio-querymodules")
+      system "gtk-update-icon-cache -ft #{CREW_PREFIX}/share/icons/*", exception: false if File.file?("#{CREW_PREFIX}/bin/gtk-update-icon-cache")
+      system "update-mime-database #{CREW_PREFIX}/share/mime" if File.file?("#{CREW_PREFIX}/bin/update-mime-database")
+      return unless File.file?("#{CREW_PREFIX}/bin/gdk-pixbuf-query-loaders")
+
+      system 'gdk-pixbuf-query-loaders',
+             '--update-cache'
```
Comment (uberhacker) [inline lib/buildsystems/autotools.rb:52]: Why not add this to `lib/package.rb` postinstall too?

Comment (uberhacker) [reply lib/buildsystems/autotools.rb:52]: Or better yet, add it to lib as a helper function and require to call one-liners in these buildsystems libraries?

Comment (satmandu) [reply lib/buildsystems/autotools.rb:52]: I'm wondering if this should be pulled out and dropped into its own thing, like `print_source_bashrc`...

Comment (uberhacker) [reply lib/buildsystems/autotools.rb:52]: That's what I was thinking.

File: tools/packages.yaml [hunk 4]
```diff
@@ -7181,6 +7186,11 @@ url: https://github.com/pypa/hatch/releases
 activity: medium
 ---
 kind: url
+name: py3_lxml
+url: https://github.com/lxml/lxml/releases
+activity: high
+---
+kind: url
```
Comment (uberhacker) [inline tools/packages.yaml:7193]: Add js115 and libpeas2 here too?

**Comment by satmandu** [comment]
Builds done. Now just working on refactoring the `gnome` function...

File: bin/crew [hunk 5]
```diff
@@ -155,7 +155,33 @@ class ExitMessage
...
+      system "gio-querymodules #{CREW_LIB_PREFIX}/gio/modules" if File.file?("#{CREW_PREFIX}/bin/gio-querymodules")
+      system "gtk-update-icon-cache -ft #{CREW_PREFIX}/share/icons/*", exception: false if File.file?("#{CREW_PREFIX}/bin/gtk-update-icon-cache")
+      system "update-mime-database #{CREW_PREFIX}/share/mime" if File.file?("#{CREW_PREFIX}/bin/update-mime-database")
+      return unless File.file?("#{CREW_PREFIX}/bin/gdk-pixbuf-query-loaders")
+
+      system 'gdk-pixbuf-query-loaders',
+             '--update-cache'
+    end
+  end
+end
```
Comment (uberhacker) [inline bin/crew:181]: Add to lib and require here instead?  The crew binary is already huge.

File: packages/libpng.rb [hunk 6]
```diff
@@ -3,22 +3,25 @@
...
   source_url 'https://git.code.sf.net/p/libpng/code.git'
   git_hashtag "v#{version}"
   binary_compression 'tar.zst'
 
   binary_sha256({
-    aarch64: '54bea8afba78bd2388704137d49b5151a9d0f8dcaafacff02436ec510e2ae627',
-     armv7l: '54bea8afba78bd2388704137d49b5151a9d0f8dcaafacff02436ec510e2ae627',
+    aarch64: 'ea5f9f73bd232972fdbf3c6d3d14da99c03af1b6d4e547e6faf59ad7ad73c3e2',
+     armv7l: 'ea5f9f73bd232972fdbf3c6d3d14da99c03af1b6d4e547e6faf59ad7ad73c3e2',
        i686: 'd4516093258bc90eecb4cc4bfd16cd5540a6e056806df37b43695b8b9137982a',
```
Comment (uberhacker) [inline packages/libpng.rb:16]: No i686 update?

Comment (satmandu) [reply packages/libpng.rb:16]: building that now...

File: packages/glade.rb [hunk 7]
```diff
@@ -22,15 +22,8 @@ class Glade < Package
...
-    system 'meson configure build'
-    system 'ninja -C build'
-  end
+  gnome
 
-  def self.install
-    system "DESTDIR=#{CREW_DEST_DIR} ninja -C build install"
-  end
+  pre_meson_options "CFLAGS='-fuse-ld=lld' CXXFLAGS='-fuse-ld=lld'"
+  meson_options '-Dgtk_doc=false -Dman=false build'
```
Comment (Zopolis4) [inline packages/glade.rb:28]: shouldn't this be `meson_options '-Dgtk_doc=false -Dman=false'`?

Comment (satmandu) [reply packages/glade.rb:28]: Yes.

**Comment by Zopolis4** [comment]
Could we implement the gnome postinstalls by just setting a boolean rather than adding to a numeric variable?

File: packages/blender.rb [hunk 8]
```diff
@@ -19,6 +40,8 @@ def self.install
   end
 
   def self.postinstall
-    puts "\nType 'blender' to get started.\n".lightblue
+    puts
+    puts "Type 'blender' to get started.".lightblue
```
Comment (Zopolis4) [inline packages/blender.rb:44]: Would this be better suited as an `ExitMessage`? (not sure exactly what the purpose of this postinstall is, to be honest, but even still it does seem to be better suited as an `ExitMessage`.

Comment (satmandu) [reply packages/blender.rb]: Made that change... But Blender doesn't actually work. It's there for debugging purposes.

**Comment by satmandu** [comment]
> Could we implement the gnome postinstalls by just setting a boolean rather than adding to a numeric variable?

That would be cleaner...

File: packages/adwaita_icon_theme.rb [hunk 9]
```diff
@@ -23,9 +23,9 @@ class Adwaita_icon_theme < Meson
   depends_on 'vala' => :build
   depends_on 'xdg_base'
 
+  gnome
+
   def self.postinstall
-    # Update mime database.
-    system "update-mime-database #{CREW_PREFIX}/share/mime"
     # This is skipped when DESTDIR is set during build.
     system "gtk-update-icon-cache -qtf #{CREW_PREFIX}/share/icons/Adwaita" if File.file?("#{CREW_PREFIX}/bin/gtk-update-icon-cache")
```
Comment (Zopolis4) [inline packages/adwaita_icon_theme.rb:30]: It looks like we can probably drop this-- `lib/gnome.rb` runs `gtk-update-icon-cache` on `CREW_PREFIX/share/icons` which should cover `CREW_PREFIX/share/icons/Adwaita`.

File: packages/baobab.rb [hunk 10]
```diff
@@ -1,42 +1,41 @@
...
+  depends_on 'pango' => :build
+  depends_on 'gtk4' => :build
+  depends_on 'libadwaita' => :build
+  depends_on 'cairo' # R
+  depends_on 'harfbuzz' # R
   depends_on 'glib' # R
   depends_on 'glibc' # R
-  depends_on 'harfbuzz' # R
-  depends_on 'pango' # R
   depends_on 'gtk4' # R
```
Comment (Zopolis4) [inline packages/baobab.rb:36]: Couple things-- these dependencies arent alphabetical, and we have `gtk4` twice (and also `gtk3`? does it actually use both?)

I'm working on something to lint stuff ilke this, but a manual review every so often will suffice in the meantime.

**Comment by satmandu** [comment]
> Could we implement the gnome postinstalls by just setting a boolean rather than adding to a numeric variable?

Changed the logic to boolean.

File: packages/blender.rb (hunk 8 above)
Comment (Zopolis4) [reply packages/blender.rb]: Yeah-- just wondering what the value of telling the user to type the name of the package to use the package is, for when blender does start working.

File: packages/baobab.rb (hunk 10 above)
Comment (satmandu) [reply packages/baobab.rb]: Fixed this file.  I tend to change all the dependencies to `=> :build` during a build and then run the getrealdeps script to see if any of those are actual runtime deps.

Comment (satmandu) [reply packages/baobab.rb]: (Forgot to sort and cull after that step.)

File: packages/adwaita_icon_theme.rb (hunk 9 above)
Comment (satmandu) [reply packages/adwaita_icon_theme.rb]: done

File: packages/blender.rb (hunk 8 above)
Comment (satmandu) [reply packages/blender.rb]: Changed it to ExitMessage in any case...

File: packages/folks.rb [hunk 11]
```diff
@@ -24,21 +24,13 @@ class Folks < Package
...
 
-  def self.build
-    system "meson setup #{CREW_MESON_OPTIONS} \
-    -Dbluez_backend=false \
+  gnome
+
+  meson_options '-Dbluez_backend=false \
     -Ddocs=false \
     -Deds_backend=false \
     -Dinstalled_tests=false \
```
Comment (Zopolis4) [inline packages/folks.rb:32]: Do we need `-Dinstalled_tests=false` if we have `-Dtests=false`?

File: packages/gcab.rb [hunk 12]
```diff
@@ -22,21 +22,13 @@ class Gcab < Package
   depends_on 'glibc' # R
   depends_on 'zlibpkg' # R
 
-  def self.prebuild
+  gnome
+
+  def self.patch
     system "sed -i 's,-fstack-protector-strong,-fno-stack-protector,' meson.build"
```
Comment (Zopolis4) [inline packages/gcab.rb:28]: This could probably be implemented with something like `pre_meson_options`, no?

File: packages/folks.rb (hunk 11 above)
Comment (satmandu) [reply packages/folks.rb:32]: Looking at https://gitlab.gnome.org/GNOME/folks/-/blob/master/meson_options.txt?ref_type=heads I see:

```
# Test options
option('tests', type: 'boolean', value: true, description: 'Build tests programs')
option('installed_tests', type: 'boolean', value: false, description: 'Install test programs')
```

File: packages/gcab.rb (hunk 12 above)
Comment (satmandu) [reply packages/gcab.rb:28]: Honestly, it might not even need that line... I didn't check for a package update to see if it now builds without it. I just converted it to our current format.

File: packages/gnome_online_accounts.rb [hunk 13]
```diff
@@ -26,15 +26,7 @@ class Gnome_online_accounts < Package
...
-    builddir"
-    system 'meson configure --no-pager builddir'
-    system 'ninja -C builddir'
-  end
+  gnome
 
-  def self.install
-    system "DESTDIR=#{CREW_DEST_DIR} ninja -C builddir install"
-  end
+  meson_options '-Dgtk_doc=true'
```
Comment (Zopolis4) [inline packages/gnome_online_accounts.rb:31]: Aren't we normally disabling documentation?

File: packages/gnome_session.rb [hunk 14]
```diff
@@ -37,17 +37,9 @@ class Gnome_session < Package
...
-      builddir"
-    system 'meson configure --no-pager builddir'
-    system 'ninja -C builddir'
-  end
+  gnome
 
-  def self.install
-    system "DESTDIR=#{CREW_DEST_DIR} ninja -C builddir install"
-  end
+  meson_options '-Dsystemd=false \
```
Comment (Zopolis4) [inline packages/gnome_session.rb:42]: Do we need the additional `-Dsystemd_session=disable` and `-Dsystemd_journal=false` arguments if we already pass `-Dsystemd=false`?

File: packages/gnome_terminal.rb [hunk 15]
```diff
@@ -33,22 +33,15 @@ class Gnome_terminal < Package
...
-    -Dsharedstatedir=#{CREW_PREFIX}/var/local/lib \
-    builddir"
-    system 'meson configure --no-pager builddir'
-    system 'ninja -C builddir'
-  end
-
-  def self.install
-    system "DESTDIR=#{CREW_DEST_DIR} ninja -C builddir install"
-  end
+    -Dsharedstatedir=#{CREW_PREFIX}/var/local/lib"
```
Comment (Zopolis4) [inline packages/gnome_terminal.rb:44]: We already pass these values for `localstatedir` and `sharedstatedir` in `lib/const.rb`

File: packages/gnome_online_accounts.rb (hunk 13 above)
Comment (satmandu) [reply packages/gnome_online_accounts.rb:31]: Yes. I guess we should rebuild this.

File: packages/yelp.rb [hunk 16]
```diff
@@ -32,17 +32,9 @@ class Yelp < Package
...
-    system 'make'
-  end
+  gnome
 
-  def self.install
-    system "make DESTDIR=#{CREW_DEST_DIR} install"
-  end
+  configure_options '--enable-compile-warnings=minimum \
+    --enable-debug=no \
+    --disable-dependency-tracking'
```
Comment (Zopolis4) [inline packages/yelp.rb:39]: We already pass `--disable-dependency-tracking` in `lib/const.rb`

**Review by Zopolis4 — APPROVED** [review]
In terms of the package files, I've reviewed a few and have left some comments-- given that you aren't actually updating most of these, it's fine to ignore them and deal with those when the next rebuild or update occurs.

In regard to `lib/gnome.rb`, I have no problems with the current implementation of this functionality within crew-- I still feel like its best to sort this out upstream and try and find a way to get the postinstall to work even when we pass `DESTDIR`, but that doesn't need to hold back this pr.

tldr; changes to crew look good, not too fussed about the packages. good for merge.

File: packages/gnome_online_accounts.rb (hunk 13 above)
Comment (satmandu) [reply packages/gnome_online_accounts.rb]: Rebuilt.

File: packages/gcab.rb (hunk 12 above)
Comment (satmandu) [reply packages/gcab.rb]: Didn't need the line.  Updated and rebuilt.

File: packages/yelp.rb (hunk 16 above)
Comment (satmandu) [reply packages/yelp.rb]: Fixed.

File: packages/gnome_terminal.rb (hunk 15 above)
Comment (satmandu) [reply packages/gnome_terminal.rb]: Removed.

File: bin/crew [hunk 17]
```diff
@@ -7,17 +7,18 @@ require 'tmpdir'
...
 require_relative '../lib/deb_utils'
+require_relative '../lib/docopt'
+require_relative '../lib/downloader'
+require_relative '../lib/gnome'
 require_relative '../lib/package'
+require_relative '../lib/util'
 
 CREW_LICENSE = <<~LICENSESTRING
-  Copyright (C) 2013-2022 Chromebrew Authors
+  Copyright (C) 2013-2024 Chromebrew Authors
```
Comment (uberhacker) [inline bin/crew:21]: Good catch!

File: lib/gnome.rb [hunk 18]
```diff
@@ -0,0 +1,21 @@
+class GnomePostinstall
+  @gnome_postinstall = false
+
+  def self.activate
+    @gnome_postinstall = true
+  end
+
+  def self.run
+    if @gnome_postinstall
```
Comment (uberhacker) [inline lib/gnome.rb:9]: I guess I'm not understanding why this is needed.  Can't we just run when needed simply with an `if @gnome` condition?

Comment (satmandu) [reply lib/gnome.rb:9]: We only want to run these once. If you're installing a bunch of gnome dependencies, you don't want the exact same postinstall code to run a dozen times. It only needs to run once, at the end.

Comment (uberhacker) [reply lib/gnome.rb:9]: Then run it just once at the end with the `if @gnome` conditional.

Comment (Zopolis4) [reply lib/gnome.rb:9]: At the end of what exactly?

File: bin/crew [hunk 19]
```diff
@@ -795,13 +797,16 @@ def pre_install(dest_dir)
...
-  if @pkg.print_source_bashrc?
+  if @pkg.print_source_bashrc? || @pkg.gnome?
     ExitMessage.add <<~PRINT_SOURCE_BASHRC_EOT.lightblue, print_last: true
 
       To finish the installation, please execute the following:
       source ~/.bashrc
     PRINT_SOURCE_BASHRC_EOT
   end
+
+  GnomePostinstall.activate if @pkg.gnome?
```
Comment (uberhacker) [inline bin/crew:808]: Instead of calling a method, just set the flag here.  `@gnome_postinstall = true if @pkg.gnome?`

File: bin/crew [hunk 20]
```diff
@@ -156,6 +157,7 @@ class ExitMessage
 end
 
 at_exit do
+  GnomePostinstall.run
```
Comment (uberhacker) [inline bin/crew:160]: `GnomePostinstall.run if @gnome_postinstall`?

File: bin/crew [hunk 21]
```diff
@@ -156,6 +157,15 @@ class ExitMessage
 end
 
 at_exit do
+  begin
+    gem 'activesupport'
+  rescue Gem::LoadError
+    puts ' -> install gem activesupport'
+    Gem.install('activesupport')
+    gem 'activesupport'
+  end
```
Comment (uberhacker) [inline bin/crew:166]: It's a shame the `.blank` method is not in core ruby yet.

File: packages/libnotify.rb [hunk 22]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Libnotify < Package
+class Libnotify < Meson
   description 'A library for sending desktop notifications.'
   homepage 'https://git.gnome.org/browse/libnotify'
   version '0.8.1'
```
Comment (uberhacker) [inline packages/libnotify.rb:6]: Update to version [0.8.3](https://gitlab.gnome.org/GNOME/libnotify/-/tags/0.8.3?

File: packages/atkmm16.rb [hunk 23]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Atkmm16 < Package
+class Atkmm16 < Meson
   description 'Atkmm is the official C++ interface for the ATK accessibility toolkit library.'
   homepage 'https://www.gtkmm.org/'
   version '2.28.3'
```
Comment (uberhacker) [inline packages/atkmm16.rb:6]: Update to [2.36.3](https://gitlab.gnome.org/GNOME/atkmm/-/tags/2.36.3)?

Comment (satmandu) [reply packages/atkmm16.rb:6]: That version is in `atkmm.rb`. `atkmm16` is the version with the older API.

File: packages/epiphany.rb [hunk 24]
```diff
@@ -1,9 +1,9 @@
...
 # https://github.com/archlinux/svntogit-packages/raw/packages/epiphany/trunk/PKGBUILD
 
-require 'package'
+require 'buildsystems/meson'
 
-class Epiphany < Package
+class Epiphany < Meson
   description 'A GNOME web browser based on the WebKit rendering engine'
   homepage 'https://wiki.gnome.org/Apps/Web'
   version '43.1'
```
Comment (uberhacker) [inline packages/epiphany.rb:9]: Update to [46.0](https://gitlab.gnome.org/GNOME/epiphany/-/tags/46.0)?

File: packages/evince.rb [hunk 25]
```diff
@@ -1,9 +1,9 @@
...
 # https://github.com/archlinux/svntogit-packages/raw/packages/evince/trunk/PKGBUILD
 
-require 'package'
+require 'buildsystems/meson'
 
-class Evince < Package
+class Evince < Meson
   description 'Document viewer PDF, PostScript, XPS, djvu, dvi, tiff, cbr, cbz, cb7, cbt'
   homepage 'https://wiki.gnome.org/Apps/Evince'
   version '44.rc'
```
Comment (uberhacker) [inline packages/evince.rb:9]: Update to [45.0](https://gitlab.gnome.org/GNOME/evince/-/tags/45.0)?

File: packages/folks.rb [hunk 26]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Folks < Package
+class Folks < Meson
   description 'Library to aggregates people into metacontacts'
   homepage 'https://wiki.gnome.org/Projects/Folks'
   version '0.15.5'
```
Comment (uberhacker) [inline packages/folks.rb:6]: Update to [0.15.7](https://gitlab.gnome.org/GNOME/folks/-/tags/0.15.7).

File: packages/fragments.rb [hunk 27]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Fragments < Package
+class Fragments < Meson
   description 'Fragments is an easy to use BitTorrent client for the GNOME desktop environment.'
   homepage 'https://gitlab.gnome.org/World/Fragments'
   version '2.1'
```
Comment (uberhacker) [inline packages/fragments.rb:6]: Update to [2.1.1](https://gitlab.gnome.org/World/Fragments/-/tags/2.1.1)?

File: packages/gcr_3.rb [hunk 28]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gcr_3 < Package
+class Gcr_3 < Meson
   description 'GNOME crypto package'
   homepage 'https://www.gnome.org'
   version '3.41.1'
```
Comment (uberhacker) [inline packages/gcr_3.rb:6]: Update to [4.2.1](https://gitlab.gnome.org/GNOME/gcr/-/tags/4.2.1)?

File: packages/gcr_4.rb [hunk 29]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gcr_4 < Package
+class Gcr_4 < Meson
   description 'GNOME crypto package'
   homepage 'https://www.gnome.org'
   version '4.0.0'
```
Comment (uberhacker) [inline packages/gcr_4.rb:6]: Update to [4.2.1](https://gitlab.gnome.org/GNOME/gcr/-/tags/4.2.1)?

File: packages/gcr_3.rb (hunk 28 above)
Comment (satmandu) [reply packages/gcr_3.rb:6]: That's in gcr_4

File: packages/gtk_doc.rb [hunk 30]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gtk_doc < Package
+class Gtk_doc < Meson
   description 'Documentation tool for public library API'
   homepage 'https://www.gtk.org/gtk-doc/'
   version '1.33.2-1'
```
Comment (uberhacker) [inline packages/gtk_doc.rb:6]: Update to [1.34.0](https://download.gnome.org/sources/gtk-doc/1.34/gtk-doc-1.34.0.tar.xz)?

File: packages/epiphany.rb (hunk 24 above)
Comment (uberhacker) [reply packages/epiphany.rb:9]: Fair enough.

File: packages/gcr_3.rb (hunk 28 above)
Comment (uberhacker) [reply packages/gcr_3.rb:6]: Corrected for gcr_3.

File: packages/gexiv2.rb [hunk 31]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gexiv2 < Package
+class Gexiv2 < Meson
   description 'gexiv2 is a GObject wrapper around the Exiv2 photo metadata library.'
   homepage 'https://wiki.gnome.org/Projects/gexiv2/'
   version '0.14.0'
```
Comment (uberhacker) [inline packages/gexiv2.rb:6]: Update to [0.14.2](https://download.gnome.org/sources/gexiv2/0.14/gexiv2-0.14.2.tar.xz)

File: packages/gfbgraph.rb [hunk 32]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Gfbgraph < Package
+class Gfbgraph < Autotools
   description 'GLib/GObject wrapper for the Facebook Graph API'
   homepage 'https://wiki.gnome.org/Projects/GFBGraph'
   version '0.2.4'
```
Comment (uberhacker) [inline packages/gfbgraph.rb:6]: Update to [0.2.5](https://gitlab.gnome.org/GNOME/libgfbgraph/-/tags/v_0_2_5)?

File: packages/glade.rb [hunk 33]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Glade < Package
+class Glade < Meson
   description 'User Interface Builder for GTK+ applications'
   homepage 'https://wiki.gnome.org/Apps/Glade'
   version '3.38.2'
```
Comment (uberhacker) [inline packages/glade.rb:6]: Update to [3.40.0](https://download.gnome.org/sources/glade/3.40/glade-3.40.0.tar.xz)?

File: packages/glibmm_2_4.rb [hunk 34]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Glibmm_2_4 < Package
+class Glibmm_2_4 < Meson
   description 'C++ bindings for GLib'
   homepage 'https://www.gtkmm.org'
   version '2.66.5'
```
Comment (uberhacker) [inline packages/glibmm_2_4.rb:6]: Update to [2.78.1](https://gitlab.gnome.org/GNOME/glibmm/-/tags/2.78.1)?

File: packages/gmime.rb [hunk 35]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Gmime < Package
+class Gmime < Autotools
   description 'GMime is a powerful MIME (Multipurpose Internet Mail Extension) utility library. It is meant for creating, editing, and parsing MIME messages and structures.'
   homepage 'https://developer.gnome.org/gmime/'
   version '3.2.3'
```
Comment (uberhacker) [inline packages/gmime.rb:6]: Update to [3.2.14](https://github.com/jstedfast/gmime/releases/tag/3.2.14)?

File: packages/gnome_calculator.rb [hunk 36]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_calculator < Package
+class Gnome_calculator < Meson
   description 'GNOME desktop calculator'
   homepage 'https://wiki.gnome.org/Apps/Calculator'
   version '43.0.1'
```
Comment (uberhacker) [inline packages/gnome_calculator.rb:6]: Update to [45.0.2](https://gitlab.gnome.org/GNOME/gnome-calculator/-/tags/45.0.2)?

File: packages/gnome_desktop.rb [hunk 37]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_desktop < Package
+class Gnome_desktop < Meson
   description 'Library with common API for various GNOME modules'
   homepage 'https://gitlab.gnome.org/GNOME/gnome-desktop'
   version '43'
```
Comment (uberhacker) [inline packages/gnome_desktop.rb:6]: Update to [44.0](https://gitlab.gnome.org/GNOME/gnome-desktop/-/tags/44.0)?

File: packages/gnome_docking_library.rb [hunk 38]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Gnome_docking_library < Package
+class Gnome_docking_library < Autotools
   description 'GUsb is a GObject wrapper for libusb1'
   homepage 'https://www.gnome.org/'
   version '3.28.0-0'
```
Comment (uberhacker) [inline packages/gnome_docking_library.rb:6]: Update to [3.40.0](https://github.com/GNOME/gdl/archive/refs/tags/GDL_3_40_0.tar.gz)?

File: packages/gnome_keyring.rb [hunk 39]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Gnome_keyring < Package
+class Gnome_keyring < Autotools
   description 'GNOME password and secret manager'
   homepage 'https://www.gnome.org'
   version '3.36.0-1'
```
Comment (uberhacker) [inline packages/gnome_keyring.rb:6]: Update to [46.1](https://download.gnome.org/sources/gnome-keyring/46/gnome-keyring-46.1.tar.xz)?

File: packages/gnome_maps.rb [hunk 40]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_maps < Package
+class Gnome_maps < Meson
   description 'A simple GNOME maps application'
   homepage 'https://wiki.gnome.org/Apps/Maps'
   version '43.0'
```
Comment (uberhacker) [inline packages/gnome_maps.rb:6]: Update to [45.5](https://gitlab.gnome.org/GNOME/gnome-maps/-/tags/v45.5)?

File: packages/gnome_mines.rb [hunk 41]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_mines < Package
+class Gnome_mines < Meson
   description 'GNOME Mines (formerly known as Gnomine) is minesweeper clone for GNOME'
   homepage 'https://wiki.gnome.org/Apps/Mines'
   @_ver = '3.36.1'
```
Comment (uberhacker) [inline packages/gnome_mines.rb:6]: Update to [40.1](https://download.gnome.org/sources/gnome-mines/40/gnome-mines-40.1.tar.xz)?

File: packages/gnome_nibbles.rb [hunk 42]
```diff
@@ -23,4 +23,6 @@ class Gnome_nibbles < Meson
   depends_on 'librsvg'
   depends_on 'vala' => :build
   depends_on 'wayland'
```
Comment (uberhacker) [inline packages/gnome_nibbles.rb:25]: Update to [4.0.3](https://gitlab.gnome.org/GNOME/gnome-nibbles/-/tags/4.0.3)?

File: packages/gnome_session.rb [hunk 43]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_session < Package
+class Gnome_session < Meson
   description 'The GNOME Session Handler'
   homepage 'https://gitlab.gnome.org/GNOME/gnome-session'
   version '43.0'
```
Comment (uberhacker) [inline packages/gnome_session.rb:6]: Update to [45.0](https://gitlab.gnome.org/GNOME/gnome-session/-/tags/45.0)?

File: packages/gnome_settings_daemon.rb [hunk 44]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_settings_daemon < Package
+class Gnome_settings_daemon < Meson
   description 'GNOME Settings Daemon'
   homepage 'https://gitlab.gnome.org/GNOME/gnome-settings-daemon'
   version '43.0'
```
Comment (uberhacker) [inline packages/gnome_settings_daemon.rb:6]: Update to [45.1](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/tags/45.1)?

File: packages/gnome_shell.rb [hunk 45]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_shell < Package
+class Gnome_shell < Meson
   description 'Next generation desktop shell'
   homepage 'https://wiki.gnome.org/Projects/GnomeShell'
   version '41.0'
```
Comment (uberhacker) [inline packages/gnome_shell.rb:6]: Update to [44.0](https://gitlab.gnome.org/GNOME/gnome-shell/-/releases/44.0)?

File: packages/gnome_sudoku.rb [hunk 46]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_sudoku < Package
+class Gnome_sudoku < Meson
   description 'Sudoku puzzle game for GNOME'
   homepage 'https://wiki.gnome.org/Apps/Sudoku'
   @_ver = '3.38.0'
```
Comment (uberhacker) [inline packages/gnome_sudoku.rb:6]: Update to [46.0](https://download.gnome.org/sources/gnome-sudoku/46/gnome-sudoku-46.0.tar.xz)?

File: packages/gnome_text_editor.rb [hunk 47]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_text_editor < Package
+class Gnome_text_editor < Meson
   description 'GNOME Text Editor'
   homepage 'https://gitlab.gnome.org/GNOME/gnome-text-editor'
   version '44.0'
```
Comment (uberhacker) [inline packages/gnome_text_editor.rb:6]: Update to [45.3](https://gitlab.gnome.org/GNOME/gnome-text-editor/-/tags/45.3)?

File: packages/gnome_themes_standard.rb [hunk 48]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Gnome_themes_standard < Package
+class Gnome_themes_standard < Autotools
   description 'Standard Themes for GNOME Applications.'
   homepage 'https://git.gnome.org/browse/gnome-themes-standard/'
   version '3.27.92-0'
```
Comment (uberhacker) [inline packages/gnome_themes_standard.rb:6]: Update to [3.28](https://github.com/GNOME/gnome-themes-extra/releases/tag/3.28)?

File: packages/gnome_tweaks.rb [hunk 49]
```diff
@@ -23,4 +23,6 @@ class Gnome_tweaks < Meson
   depends_on 'python3'
   depends_on 'libhandy'
   depends_on 'libnotify'
```
Comment (uberhacker) [inline packages/gnome_tweaks.rb:25]: Update to [45.1](https://gitlab.gnome.org/GNOME/gnome-tweaks/-/tags/45.1)?

File: packages/gnome_weather.rb [hunk 50]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gnome_weather < Package
+class Gnome_weather < Meson
   description 'Access current weather conditions and forecasts'
   homepage 'https://wiki.gnome.org/Apps/Weather'
   version '40.0'
```
Comment (uberhacker) [inline packages/gnome_weather.rb:6]: Update to [45.0](https://gitlab.gnome.org/GNOME/gnome-weather/-/tags/45.0)?

File: packages/gsound.rb [hunk 51]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Gsound < Package
+class Gsound < Autotools
   description 'GSound is a small library for playing system sounds.'
   homepage 'https://wiki.gnome.org/Projects/GSound'
   version '1.0.2'
```
Comment (uberhacker) [inline packages/gsound.rb:6]: Update to [1.0.3](https://download.gnome.org/sources/gsound/1.0/gsound-1.0.3.tar.xz)?

File: packages/glibmm_2_4.rb (hunk 34 above)
Comment (satmandu) [reply packages/glibmm_2_4.rb:6]: That's in glibmm_2_68...

File: packages/gnome_shell.rb (hunk 45 above)
Comment (satmandu) [reply packages/gnome_shell.rb:6]: depends upon gnome_session, which now has a hard systems dep, so deprecating.

File: packages/gnome_session.rb (hunk 43 above)
Comment (satmandu) [reply packages/gnome_session.rb:6]: Gnome_session now has a hard systems dep, so deprecating.

File: packages/gnome_settings_daemon.rb (hunk 44 above)
Comment (satmandu) [reply packages/gnome_settings_daemon.rb:6]: No longer builds w/o systemd.

Comment (satmandu) [reply packages/gnome_settings_daemon.rb:6]: deprecating.

File: packages/gnome_tweaks.rb (hunk 49 above)
Comment (satmandu) [reply packages/gnome_tweaks.rb:25]: Requires deprecated gnome_desktop_daemon, deprecating.

File: packages/gmime.rb (hunk 35 above)
Comment (satmandu) [reply packages/gmime.rb]: Does not build.

File: packages/gfbgraph.rb (hunk 32 above)
Comment (satmandu) [reply packages/gfbgraph.rb]: No package 'rest-0.7' found   ...

**Comment by satmandu** [comment]
With the glib rebuild here (rebuilt with gobject_introspection) installs will now fail until this is merged...

File: packages/gucharmap.rb [hunk 52]
```diff
@@ -20,6 +20,8 @@ class Gucharmap < Package
   depends_on 'itstool'
```
Comment (uberhacker) [inline packages/gucharmap.rb:20]: Update to [12.0.1](https://download.gnome.org/sources/gucharmap/12.0/gucharmap-12.0.1.tar.xz)?

**Comment by yeesterPlus** [comment]
it broke nautilus

File: packages/gvfs.rb [hunk 53]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Gvfs < Package
+class Gvfs < Meson
   description 'Virtual filesystem implementation for GIO'
   homepage 'https://wiki.gnome.org/Projects/gvfs'
   version '1.50.4'
```
Comment (uberhacker) [inline packages/gvfs.rb:6]: Update to [1.54.0](https://gitlab.gnome.org/GNOME/gvfs/-/tags/1.54.0)?

File: packages/json_glib.rb [hunk 54]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Json_glib < Package
+class Json_glib < Meson
   description 'JSON-GLib implements a full suite of JSON-related tools using GLib and GObject.'
   homepage 'https://wiki.gnome.org/Projects/JsonGlib'
   version '1.6.6'
```
Comment (uberhacker) [inline packages/json_glib.rb:6]: Update to [1.8.0](https://gitlab.gnome.org/GNOME/json-glib/-/tags/1.8.0)?

File: packages/jsonrpc_glib.rb [hunk 55]
```diff
@@ -1,9 +1,9 @@
...
 # https://github.com/archlinux/svntogit-packages/raw/packages/jsonrpc-glib/trunk/PKGBUILD
 
-require 'package'
+require 'buildsystems/meson'
 
-class Jsonrpc_glib < Package
+class Jsonrpc_glib < Meson
   description 'A JSON-RPC library for GLib'
   homepage 'https://gitlab.gnome.org/GNOME/jsonrpc-glib'
   version '3.42.0'
```
Comment (uberhacker) [inline packages/jsonrpc_glib.rb:9]: Update to [3.44.0](https://gitlab.gnome.org/GNOME/jsonrpc-glib/-/tags/3.44.0)?

File: packages/libchamplain.rb [hunk 56]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Libchamplain < Package
+class Libchamplain < Meson
   description 'A map widget'
   homepage 'https://wiki.gnome.org/Projects/libchamplain'
   version '0.12.20'
```
Comment (uberhacker) [inline packages/libchamplain.rb:6]: Update to [0.12.21](https://gitlab.gnome.org/GNOME/libchamplain/-/tags/0.12.21)?

File: packages/libcloudproviders.rb [hunk 57]
```diff
@@ -1,9 +1,9 @@
...
 # https://github.com/archlinux/svntogit-packages/raw/packages/libcloudproviders/trunk/PKGBUILD
 
-require 'package'
+require 'buildsystems/meson'
 
-class Libcloudproviders < Package
+class Libcloudproviders < Meson
   description 'DBus API that allows cloud storage sync clients to expose their services'
   homepage 'https://gitlab.gnome.org/World/libcloudproviders'
   version '0.3.1'
```
Comment (uberhacker) [inline packages/libcloudproviders.rb:9]: Update to [0.3.5](https://gitlab.gnome.org/World/libcloudproviders/-/tags/0.3.5)?

File: packages/libgee.rb [hunk 58]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Libgee < Package
+class Libgee < Autotools
   description 'Libgee is an utility library providing GObject-based interfaces and classes for commonly used data structures.'
   homepage 'https://wiki.gnome.org/Projects/Libgee'
   version '0.20.4'
```
Comment (uberhacker) [inline packages/libgee.rb:6]: Update to [0.20.6](https://gitlab.gnome.org/GNOME/libgee/-/tags/0.20.6)?

File: packages/libgsf.rb [hunk 59]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Libgsf < Package
+class Libgsf < Autotools
   description 'The G Structured File Library'
   homepage 'https://gitlab.gnome.org/GNOME/libgsf'
   version '1.14.50'
```
Comment (uberhacker) [inline packages/libgsf.rb:6]: Update to [1.14.52](https://gitlab.gnome.org/GNOME/libgsf/-/tags/LIBGSF_1_14_52)?

File: packages/libgtop.rb [hunk 60]
```diff
@@ -1,9 +1,9 @@
...
 # https://github.com/archlinux/svntogit-packages/raw/packages/libgtop/trunk/PKGBUILD
 
-require 'package'
+require 'buildsystems/autotools'
 
-class Libgtop < Package
+class Libgtop < Autotools
   description 'A library for collecting system monitoring data'
   homepage 'https://gitlab.gnome.org/GNOME/libgtop'
   version '2.40.0-507809b'
```
Comment (uberhacker) [inline packages/libgtop.rb:9]: Update to [2.41.3](https://gitlab.gnome.org/GNOME/libgtop/-/tags/2.41.3)?

File: packages/libgweather.rb [hunk 61]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Libgweather < Package
+class Libgweather < Meson
   description 'Location and timezone database and weather-lookup library'
   homepage 'https://wiki.gnome.org/Projects/LibGWeather'
   version '4.2.0'
```
Comment (uberhacker) [inline packages/libgweather.rb:6]: Update to [4.4.0](https://gitlab.gnome.org/GNOME/libgweather/-/tags/4.4.0)?

File: packages/libpanel.rb [hunk 62]
```diff
@@ -1,9 +1,9 @@
...
 # https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=libpanel
 
-require 'package'
+require 'buildsystems/meson'
 
-class Libpanel < Package
+class Libpanel < Meson
   description 'A dock/panel library for GTK 4'
   homepage 'https://gitlab.gnome.org/GNOME/libpanel'
   version '1.0.1'
```
Comment (uberhacker) [inline packages/libpanel.rb:9]: Update to [1.6.0](https://gitlab.gnome.org/GNOME/libpanel/-/tags/1.6.0)?

File: packages/libsoup.rb [hunk 63]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Libsoup < Package
+class Libsoup < Meson
   description 'libsoup is an HTTP client/server library for GNOME.'
   homepage 'https://wiki.gnome.org/Projects/libsoup'
   version '3.4.1'
```
Comment (uberhacker) [inline packages/libsoup.rb:6]: Update to [3.4.4](https://gitlab.gnome.org/GNOME/libsoup/-/tags/3.4.4}?

File: packages/libwnck.rb [hunk 64]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Libwnck < Package
+class Libwnck < Meson
   description 'Library for layout and rendering of text'
   homepage 'http://www.gnome.org/'
   version '3.32.0'
```
Comment (uberhacker) [inline packages/libwnck.rb:6]: Update to [43.0](https://download.gnome.org/sources/libwnck/43/libwnck-43.0.tar.xz)

File: packages/mobile_broadband_provider_info.rb [hunk 65]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Mobile_broadband_provider_info < Package
+class Mobile_broadband_provider_info < Autotools
   description 'Network Management daemon'
   homepage 'https://gitlab.gnome.org/GNOME/mobile-broadband-provider-info'
   version '20201225'
```
Comment (uberhacker) [inline packages/mobile_broadband_provider_info.rb:6]: Update to [20230416](https://gitlab.gnome.org/GNOME/mobile-broadband-provider-info/-/tags/20230416)?

File: packages/nautilus.rb [hunk 66]
```diff
@@ -1,9 +1,9 @@
...
 # https://github.com/archlinux/svntogit-packages/raw/packages/nautilus/trunk/PKGBUILD
 
-require 'package'
+require 'buildsystems/meson'
 
-class Nautilus < Package
+class Nautilus < Meson
   description 'Default file manager for GNOME'
   homepage 'https://wiki.gnome.org/Apps/Files'
   version '44.2'
```
Comment (uberhacker) [inline packages/nautilus.rb:9]: Update to [45.2.1](https://gitlab.gnome.org/GNOME/nautilus/-/tags/45.2.1)?

File: packages/networkmanager.rb [hunk 67]
```diff
@@ -28,7 +28,8 @@ class Networkmanager < Meson
   depends_on 'elogind'
```
Comment (uberhacker) [inline packages/networkmanager.rb:28]: Update to  [1.44.4](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/tags/1.44.4)?

File: packages/pangomm_1_4.rb [hunk 68]
```diff
@@ -26,5 +26,7 @@ class Pangomm_1_4 < Meson
   depends_on 'mm_common' => :build
```
Comment (uberhacker) [inline packages/pangomm_1_4.rb:26]: Update to [2.52.0](https://gitlab.gnome.org/GNOME/pangomm/-/tags/2.52.0)

File: packages/rhythmbox.rb [hunk 69]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/autotools'
 
-class Rhythmbox < Package
+class Rhythmbox < Autotools
   description 'Rhythmbox is a music playing application for GNOME.'
   homepage 'https://wiki.gnome.org/Apps/Rhythmbox'
   version '3.4.4'
```
Comment (uberhacker) [inline packages/rhythmbox.rb:6]: Update to [3.4.7](https://download.gnome.org/sources/rhythmbox/3.4/rhythmbox-3.4.7.tar.xz)?

File: packages/tepl_5.rb [hunk 70]
```diff
@@ -1,6 +1,6 @@
-require 'package'
+require 'buildsystems/meson'
 
-class Tepl_5 < Package
+class Tepl_5 < Meson
   description 'Library that eases the development of GtkSourceView-based text editors and IDEs'
   homepage 'https://wiki.gnome.org/Projects/Tepl'
   @_ver = '5.0.1'
```
Comment (uberhacker) [inline packages/tepl_5.rb:6]: Update to [5.1.1](https://gitlab.gnome.org/Archive/tepl/-/tags/5.1.1)?

File: packages/tracker3_miners.rb [hunk 71]
```diff
@@ -43,6 +43,8 @@ class Tracker3_miners < Meson
   depends_on 'util_linux' # R
```
Comment (uberhacker) [inline packages/tracker3_miners.rb:43]: Update to [3.6.2](https://gitlab.gnome.org/GNOME/tracker-miners/-/tags/3.6.2)?

File: packages/libgee.rb (hunk 58 above)
Comment (satmandu) [reply packages/libgee.rb:6]: Doesn't build.

File: packages/pangomm_1_4.rb (hunk 68 above)
Comment (satmandu) [reply packages/pangomm_1_4.rb:26]: I think that would be pango_2_48...

**Comment by satmandu** [comment]
> nautilus

Try please with the build I just uploaded.

File: packages/rhythmbox.rb (hunk 69 above)
Comment (satmandu) [reply packages/rhythmbox.rb]: Updated on arm.

**Review by uberhacker — APPROVED** [review]
